### ISSUE TITLE
[Protobuf] test_package must generate addressbook.pb.h and addressbook.pb.cc

### ISSUE THREAD

**Issue by wizardsd** [bincrafters/community#1007]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **Protobuf/3.9.1**

The `test_package` subdirectory of `conan-protobuf` package contains `addressbook.pb.cc` and `addressbook.pb.h` files. These files must be generated at build time using `protoc` and not included in `test_package`

Consider using `find_package(Protobuf REQUIRED)`, `protobuf_generate_cpp(...)` in `CMakeLists.txt`, as described in [FindProtobuf example section](https://cmake.org/cmake/help/latest/module/FindProtobuf.html) to generate such files.

**Comment by uilianries** [comment]
Do you have any trouble using the current design? Otherwise we won't change it.

Protobuf and Protoc are separated packages, to avoid extra package download, the test package doesn't use protoc package.

**Comment by ruipires** [comment]
I'm having some trouble understanding the current state of the protobuf package.

I see https://github.com/bincrafters/conan-protoc_installer is marked as obsolete, because it was merged into the protobuf conan package.

But it does not seem to actually install the protoc compiler.

There is https://github.com/bincrafters/conan-protobuf/pull/34 
Is this a temporary situation, that will be solved by that pull request ?
Or am I doing something wrong ?

Ideally protobuf would add the builddirs  and build_modules properties introduced in conan 1.20 and have the protobuf auxiliary cmake files automatically included, as well as the protoc executable itself.

I think it is reasonable to expect that the test_package generates the .h and .cc files from the .proto file instead.

**Comment by uilianries** [comment]
> because it was merged into the protobuf conan package.

No. The recipe was moved to https://github.com/bincrafters/conan-protobuf. Both Conan packages are separated, we have 2 packages: `protoc_installer` and `protobuf`.

> Ideally protobuf would add the builddirs and build_modules properties introduced in conan 1.20 and have the protobuf auxiliary cmake files automatically included, as well as the protoc executable itself.

It's true, it can be improved.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
