### ISSUE TITLE
OpenCV and Qt conflict

### ISSUE THREAD

**Issue by AlexandrePTJ** [bincrafters/community#1010]
I have the following conanfile.txt:

```
[requires]
qt/5.13.1@bincrafters/stable
opencv/4.1.1@conan/stable

[generators]
cmake
```

### Conan profile
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++
build_type=Debug
[options]
[build_requires]
[env]
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
```

### Steps to reproduce (Include if Applicable)
Just run conan install

### Logs (Include/Attach if Applicable)
```
ERROR: Conflict in opencv/4.1.1@conan/stable
    Requirement zlib/1.2.11@conan/stable conflicts with already defined zlib/1.2.11
    To change it, override it in your base requirements
```

###
I don't really understand why it raise a conflict error.

I tried to override as requested, but then I raised another error but with bzip2, also with same versions.

**Comment by ericLemanissier** [comment]
This happens because qt recipe migrates its requirements to conan center index reference (without `@user/channel` suffix), whereas opencv did not do it yet. Conan errors out because it detects that 2 packages of the dependency graph are requiring a package with the same name (zlib here), but with different version, user, or channel. The situation should improve when https://github.com/conan-community/conan-opencv/pull/33 is merged. In the meantime, you can override the requirements as explained in the error message (probably for several packages)

**Comment by AlexandrePTJ** [comment]
Ok thanks for the information. I will wait for the merge.
