### ISSUE TITLE
[QT] Question: License really only LGPL in "qt:bincrafter" as oppose to "Qt:bincrafter"

### ISSUE THREAD

**Issue by imi0** [bincrafters/community#1048]
On Package "qt:bincrafter" (small caps), https://bintray.com/bincrafters/public-conan/qt%3Abincrafters the license is stated as "LGPL-3.0" only.

On the deprecated package "Qt:bincrafter" at https://bintray.com/bincrafters/public-conan/Qt%3Abincrafters the license is "LGPL-3.0 | GPL-2.0 | QTPL-1.0".

Is this by mistake or intentionally?

**Comment by ericLemanissier** [comment]
since 5.7, Qt (the upstream project) is licensed under [either LGPL V3 or commercial license](https://doc.qt.io/qt-5/licensing.html). before that [LGPL V2.1 was also possible](https://doc.qt.io/archives/qt-5.6/licensing.html)
Regarding your question, I don't know where this `LGPL-3.0 | GPL-2.0 | QTPL-1.0` license comes from, because most the the recipes in this project have `license = "http://doc.qt.io/qt-5/lgpl.html"`
Anyway, you should not use the `Qt` recipes, only `qt` is maintained now.

**Comment by imi0** [comment]
Thanks, Eric for the clarification. So to summarize, is the following correct?

- [QT](https://www.qt.io/) is licensed under the dual [LGPLV3+commercial](https://doc.qt.io/qt-5/licensing.html) licenses. I need to comply to these, if I use QT in my app (regardless of how I build my application - using conan or whatever)
- The [conan-qt](https://bintray.com/bincrafters/public-conan/qt%3Abincrafters) recipes which are downloading the QT are licensed (only) under LGPL. I "only" need to comply to that license, if I have changes to the conan recipes.
- Don't use the [deprecated Qt](https://bintray.com/bincrafters/public-conan/Qt%3Abincrafters) anymore.

Right?

**Comment by ericLemanissier** [comment]
Your first and third items are right. Second item is not: the conan-qt recipe is licensed under MIT, as can be seen on https://github.com/bincrafters/conan-qt/blob/testing/5.13.2/LICENSE.md.

**Comment by ShamanTcler** [comment]
I am considering keeping developers on Qt 5.6 specifically to avoid the LGPL 3.0 license change.

Is it reasonable to ask bincrafter's to provide the appropriate binaries/recipe whenever a library makes big changes to a license? 

So in this case in N years I see Qt 5.6 (LTS) and Qt 5.9 (LTS), 5.1X (last qt before 6?)  Qt 6.0, 6.1,6.2

**Comment by Croydon** [comment]
5.6 is end of life since 2019-03-16, writing a Conan recipe for this version now is unwise, sorry.

> So in this case in N years I see Qt 5.6 (LTS) and Qt 5.9 (LTS), 5.1X (last qt before 6?) Qt 6.0, 6.1,6.2

Except 5.6 -> 5.7 this seems unrelated to licensing?

@ericLemanissier is currently maintaining the latest LTS (5.12) and the latest non-LTS version (thanks!), I don't think we have enough contributors for doing more

**Comment by ShamanTcler** [comment]
5.6 was the last lgpl 2.1, then  5.7 was the first lgpl 3.0.

Qt is just getting REALLY ugly over licensing. I certainly understand resource limitations. Thanks for all you do.

**Comment by Croydon** [comment]
Thanks for understanding.

@imi0 Was your question answered?
