### ISSUE TITLE
Troubleshoot conan-gmp on travis - and reduce logs

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#109]
I'm not sure if it's possible, but it would be helpful if someone looked for a way to reduce verbosity.  With the default build verbosity, the log is excessively long and gets truncated on travisci.  This is a problem because builds occasionally fail randomly and obviously, it's harder to debug when you can't see the logs before it fails.  

### Package Details (Include if Applicable)
* Package Name/Version: `gmp/6.1.2@bincrafters/testing`
* Operating System: **Linux**
* Compiler+version: all
* Docker image: all

**Comment by solvingj** [comment]
It turns out that the GCC builds are failling for some reason as well: 
https://travis-ci.org/bincrafters/conan-gmp

**Comment by dimi309** [comment]
This looks like a timeout... Maybe it's due to the availability of travis resources at the time of the build. I would try to relaunch the individual builds a couple of times because I don't see any fundamental difference between this latest version and the one that produced this successful build some time ago https://travis-ci.org/bincrafters/conan-gmp/builds/328454428?utm_source=github_status&utm_medium=notification

At the moment, I am not quite sure how to limit verbosity and some quick looking around did not help discover any way to do so, unfortunately. If someone knows how to do this with a cmake or make parameter, or some other way, please let us know.

**Comment by solvingj** [comment]
Closing as apparently due to timeouts.

**Comment by solvingj** [comment]
Not due to timeouts.

**Comment by SSE4** [comment]
I've split builds into pages, we'll see how is it going

**Comment by SSE4** [comment]
closing as build passed
