### ISSUE TITLE
Package libogg

### ISSUE THREAD

**Issue by sztomi** [bincrafters/community#11]
[libogg](https://xiph.org/downloads/)

WIP here: https://github.com/sztomi/conan-libogg

Status:

 - [x] macOS (local)
 - [x] Linux (local)
 - [x] Travis CI
 - [x] Windows (local)
 - [x] AppVeyor
 - [ ] Move to bincrafters

**Comment by sztomi** [comment]
When building the shared configurations on Travis, I'm getting

```
/usr/bin/ld: skipping incompatible /<long path>/libogg.so when searching for -logg
```

which I can't reproduce locally. The same thing happens on Linux Mint and macOS. I remember seeing this earlier with fmt, but I don't know what the fix was, because someone else fixed it for me. Any ideas?

**Comment by sztomi** [comment]
Fixed the problem - I removed the CMake wrapper by mistake. Re-adding it fixed the problem.

**Comment by sztomi** [comment]
Travis CI success: https://travis-ci.org/sztomi/conan-libogg/builds/311015494

**Comment by sztomi** [comment]
AppVeyor: https://ci.appveyor.com/project/sztomi/conan-libogg

**Comment by solvingj** [comment]
Is this package any different than the one we have here?
https://github.com/bincrafters/conan-ogg

**Comment by dimi309** [comment]
@sztomi I would suggest you use the one on bincrafters. I have been using it for years before adding it there and it has some details perfected like fPIC, original license copying, a FindOGG cmake module for "legacy" project inclusion and avoidance of little bugs and glitches I have fixed here and there. Most importantly, it is referenced by the bincrafters vorbis package we talked about yesterday.

**Comment by sztomi** [comment]
wow, I'm facepalming hard now. No, it's not different at all, @solvingj. Bintray search is totally broken (try searching for `ogg` there). 

![](https://i.imgur.com/U74nYWo.png)

It's not on the next 5 pages either, I didn't look further. 

If I change the sorting to "by name", ogg becomes the only result:

![](https://i.imgur.com/hcZc3Sj.png)

Maybe we should report this to JFrog, because it affects us when a casual user checks out the repo to see if a package they want is available.

**Comment by dimi309** [comment]
It's true that bintray search is a bit wanting, at least for conan packages. One trick I do is to add the :bincrafters suffix when I search. It makes it run faster.. And another thing, let me know if I'm wrong, but don't you guys think it might be good if we avoid prefixing packages with "lib" when we publish them? I mean as in not creating packages named "libogg" or "libvorbis" for example and just calling them "ogg" and "vorbis". It may make for a more intuitive convention and anyway, in my humble opinion, the lib part is just three characters that don't convey any useful information, since everything is a lib anyway. (Of course I'm always for leaving existing packages as they are and not messing with them too much or, at least, not too quickly)

**Comment by sztomi** [comment]
I vote for consistency, be it with or without the lib part. Seeing how most (all?) our packages don't have the lib prefix I think it makes sense to keep it that way.

**Comment by dimi309** [comment]
Thanks @sztomi !

**Comment by solvingj** [comment]
@sztomi I feel really sorry for you.  So, if you type Ogg, and hit "enter" twice after entering your search term, it comes up.  It has confused me several times.  For what it's worth, Bintray is working on new UI, expected to be out in a few months.

**Comment by sztomi** [comment]
that's alright, it was a good learning experience anyway :)
