### ISSUE TITLE
[libmpg123] Migrate builds to upstream CMake files with 1.25.13+

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#1154]
I have patched the current recipe versions to use CMake already with the upstream SVN files.

This allowed to get rid of nasty Windows registry hacks and similar bad stuff: https://github.com/bincrafters/conan-libmpg123/commit/d624d49428a2a854861b7194c418fde61ea673cd

I think the CMake patching is the smaller evil, but obviously not ideal.

As soon as the next libmpg123 release happens we should migrate to the official CMake files.

Places to watch:
https://www.mpg123.de/cgi-bin/news.cgi
https://sourceforge.net/projects/mpg123/
https://www.mpg123.de/cgi-bin/scm/mpg123/trunk/ports/
https://www.mpg123.de/cgi-bin/scm/mpg123/tags/?pathrev=4592

**Comment by Croydon** [comment]
1.26.0 is not released with upstream CMake

Waiting for 1.26.1 for several CMake bug fixes

**Comment by Croydon** [comment]
Actually, 1.26.1 is already released

**Comment by Croydon** [comment]
Waiting for 1.26.1+ to get even more patches upstreamed

**Comment by Croydon** [comment]
VS2015 and 2017 fail with 1.26.2 

https://github.com/bincrafters/conan-libmpg123/commit/ff1fbc73dceaf94c96d57fb67ad19c8042df0085

**Comment by Croydon** [comment]
//cc @ledocc

**Comment by ledocc** [comment]
when build with Visual Studio 2015 and 2017, an error occur when link [tabinit_mmx.S.obj](https://ci.appveyor.com/project/bincrafters/conan-libmpg123/builds/35112581/job/8hm05p3xswykea9x#L729). 
tabinit_mmx.S should be used when libmpg123 is build for x86 target as defined in libmpg123 [CMakeLists.txt](https://www.mpg123.de/cgi-bin/scm/mpg123/trunk/ports/cmake/src/libmpg123/CMakeLists.txt?view=markup#l94), but the architecture target is x86_64. 
This problem occur only with appveyor image Visual Studio 2015 and 2017, and this images use cmake 3.16.2, and Visual Studio 2019 image use cmake 3.18.2 [see there](https://www.appveyor.com/docs/windows-images-software/#tools). I suspect CMake 3.16.2 to not correctly set CMAKE_GENERATOR_PLATFORM and assembly version of "tabinit" code is used instead of C version.
can you force cmake 3.18.2 or above installation on Visual Studio 2015 and 2017 appveyor's image to test this ?

**Comment by Croydon** [comment]
I started a CI Job, which outputs the `CMAKE_VERSION` and `CMAKE_GENERATOR_PLATFORM`:

https://ci.appveyor.com/project/bincrafters/conan-libmpg123/builds/35276596

and here is a run with `cmake/3.18.2` on all Windows jobs: 

https://ci.appveyor.com/project/bincrafters/conan-libmpg123/builds/35276647

For CMake 3.16.2 on AppVeyor with VS 2015 `CMAKE_GENERATOR_PLATFORM` isn't defined at all

https://ci.appveyor.com/project/bincrafters/conan-libmpg123/builds/35276596/job/4qs903aspou4f3ah#L276

And the same thing for CMake 3.12 on AppVeyor with VS 2017:

https://ci.appveyor.com/project/bincrafters/conan-libmpg123/builds/35276596/job/rhoaomvhlpkqlx3e#L281

**Comment by Croydon** [comment]
Same result for the run with `cmake/3.18.2`

**Comment by ledocc** [comment]
ok, I will create a VM with windows, install MSVC 2015 and try on my side.

**Comment by Croydon** [comment]
I can also add you as an contributor to this repository, if you would like to debug on our CI 😄

**Comment by Croydon** [comment]
I have invited you. Feel free to push to own branches in the form of `<something-something>/<version-number>` if you like

**Comment by Croydon** [comment]
Done via https://github.com/conan-io/conan-center-index/pull/3630
