### ISSUE TITLE
[Discussion] sharing code between package recipes

### ISSUE THREAD

**Issue by r-darwish** [bincrafters/community#116]
The creation of `bincrafters_package_tools` had greatly reduced the amount of code duplication in
our templates. It also makes updates much easier. There is still duplicated code in the package
recipes, so that area can benefit from a similar change.

However, we can't just start using 3rd party dependencies in our recipes because it forces package
users to install them manually, which breaks the whole idea of "Conan takes care of the dependencies
for me".

I'd like to discuss the idea of which recipe code can be exported to a third party package, assuming
that Conan can handle such scenario. If this idea seem beneficial enough, then we can request the
proper feature from Conan. I suppose that a solution can be made possible by having Conan manage its
own virtualenv.

From what I can think of at the moment, here are some code snippets which we duplicate among
multiple packages:

* Our standard `source` function of getting and extracting the source code from Github.
* Our standard `package` function which copies all the required artifacts.
* A utility function for extending `self.cpp_info.libs` based on the OS (Such as adding `ws2_32`
  only in Windows)

**Comment by solvingj** [comment]
It's good to bring this up in a github issue. There has been substantial discussion in Slack and possibly issues over on the Conan github.  Conan team is certainly aware of, and exploring various strategies, as this need actually impacts the enterprise use cases as much as OSS (if not more).  

As of December, the best strategy was what we did for Boost, and here is an example of that: 
https://github.com/bincrafters/conan-boost_callable_traits/blob/stable/1.66.0/conanfile.py

This features a lot of boilerplate, but keeps the general spirit and form of the Conanfile.  One of the big question is whether or not sub-classing Conanfile via inheritance is a good idea overall.  

We'll see if the Conan team has had any updates or new ideas on the topic since December.

**Comment by SSE4** [comment]
this might be related https://github.com/conan-io/conan/issues/1271

**Comment by sourcedelica** [comment]
Yes, #1271 is the right one.  It looks like the Conan team is going to be providing a good solution soon.  It is a huge issue for the enterprise use case and the current workarounds are ugly.

**Comment by solvingj** [comment]
I just now got around to reading this proposal and I think it's absolutely on the right track. Thank you so much for spending time on this.  I think I will likely use to implement and test new ideas and features for Conan in my own environment before proposing them with a PR.  It's somewhat similar to custom Conan Generators in it's testability and sharability.

**Comment by SSE4** [comment]
conan has added `python_requires` feature (experimental) in 1.7 release
I am closing the issue as it's already covered
