### ISSUE TITLE
[question] Request for taking maintaining some conan recipes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [bincrafters/community#1172]
Hi!
Thank you a lot for a job you do! It really helps a lot in every day C++ programming.
For some my perosnal needs I've packaged several libraries to Conan. Unfortunately I have no enough time to maintain packages as a part of Bincrafters (sorry for that).

But it will be fine if other people can use my Conan recipes from some trusted place (like Bincrafters repo).

Below there are some links for my recipes:
* https://github.com/ZaMaZaN4iK/conan-tinyfsm
* Also I've a request for inlcusion into Conan Center Index. but seems like Conan people has a lot of work and my request can be forgotten: https://github.com/conan-io/conan-center-index/pull/1193

Probably anyone from Bincrafters can push any of the recipe above.

Thank you a lot!

**Comment by uilianries** [comment]
I prefer having your recipe there in CCI. That recipe looks good and you only need to wait EAP approval (I have no permission to approve).

**Comment by uilianries** [comment]
Usually, the approval is made in waves

**Comment by ZaMaZaN4iK** [comment]
@uilianries that's a little bit strange situation for now. Where people should contribute their recipes to get them widely-accessible from "central" repos? There are only conan-center/bincrafters. Recommended way for now as far as I can understand is conan-center-index, but people cannot contribute to the conan-center-index. I am a little bit disappointed :)

**Comment by uilianries** [comment]
Unfortunately the response is not quickly in CCI because people are more focused fixing the server. Please, don't be disappointed, it is an Early-Acccess-Program, we are testing, trying new features, and most important, getting it stable. Now think we approving you PR, merging, but for some reason is broken in remote, not available, etc. We have some strange cases there, that need investigation first, to prevent any possible replication for other packages.

Let's keep it in Bincrafters, and when available in CCI, we can deprecate. That's what I can do for now.

**Comment by uilianries** [comment]
@ZaMaZaN4iK Done: https://github.com/bincrafters/conan-tinyfsm

**Comment by ZaMaZaN4iK** [comment]
@uilianries Thank you a lot! I think it can be closed.
