### ISSUE TITLE
conan-qt 5.15.0 no longer includes with_mesa 

### ISSUE THREAD

**Issue by EugenMayer** [bincrafters/community#1205]
I'am trying to compile conan-qt 5.15.0 but i get the error that the option does no longer exist. 

Are there any upgrade notes or how did that happen? Any upgrade stream i can follow to understand what is changed?

It was added here https://github.com/bincrafters/conan-qt/commit/7c2f5bf147a609fb3ecd40549b3de30c21e63d41 

and removed with https://github.com/bincrafters/conan-qt/commit/36f7702b142244cd503e12891d8bc7ac5d37504e#diff-2b1d42f71f22b7ea0412d7602dec166f

**Comment by ericLemanissier** [comment]
We migrated the direct dependency `mesa/20.0.1@bincrafters/stable` to `opengl/virtual@bincrafters/stable`. By default `opengl/virtual` does not compile nor package anything, it just acts as a proxy to the opengl system package. If you where setting `qt:with_mesa=False` then you don't have to do anything. If you want to use the mesa provided by conan, then you have to set `opengl:provider=conan`

**Comment by EugenMayer** [comment]
@ericLemanissier thanks - is there any way to follow this changes somehow, are there any changelogs or similar? issues to see why things changed?

**Comment by ericLemanissier** [comment]
Unfortunately I don't have (or take the) time for such documentation. the only for you to keep up is to inspect https://github.com/bincrafters/conan-qt/commits/HEAD. Usually when a commit fixes a reported issue I put a link in the commit message.
I know this lack of documentation has been pointed out several times, so if you know some conan packages maintaining changelogs/release notes, I'd be happy to take a look to see how I could do something similar

**Comment by EugenMayer** [comment]
I understand that writing those changelogs and docs is one of the less beloved tasks, but considering how valuable some of your conan reciepes are and how many people will/are using it, it would really add a great value if you would write up your "public API changes".

- Be it that what changes in the dynamic-linking / static linking in glibc 
- which flags are removed ( or added )
- what defaults have been changed
- What new dependencies have been added ( or removed )
- Which dependencies have been upgraded

The point here is, the above are the "packager changelogs", the changelogs of QT are something else and you do not need to care about.

Do not take this as an offense though, having you put all the time into the projects to keeping them maintained and up to date is already a huge value. I just think you would golden your work / add huge value by making the "public API" changes a little less harder to track.

Would close this issue though, the build worked and i think we have enough information for google for others to find the issue. If not, feel free to adjust whatever you think is needed.

Thanks!

**Comment by ericLemanissier** [comment]
I'm not offended don't worry ;) I completely understand why it is needed. I was asking if you know of other package doing such changelogs, because I'm don't know the right vehicle for this information, the main objective being to reach most users, in the easiest way.

1. README.md on the repository does not seem like a good solution because it is not redistributed with the recipe, and I guess most user just consume the recipe from bintray without ever going to github
2. we could create a CHANGELOG.md exported with the recipe
3. we could simply maintain a changelog in a comments section in the recipe
4. we could include the changelog [in the file created by the markdown generator](https://docs.conan.io/en/latest/reference/generators/markdown.html). this is not possible until https://github.com/conan-io/conan/issues/6771 is fixed

One last precision, the change of the default linking in glib (not glibc) would not appear anywhere in qt recipe's changelog, because it happened in the glib package. What this shows is that users need to go check the changelogs of ALL the packages in the dependency graph, not only the direct requirements. This is why I think option 4 is the best: it gathers the information of all the packages in a single folder

**Comment by EugenMayer** [comment]
I think there are 2 options:

- Using CHANGELOG - that is one of the older ways and still works today. Most people will see and read that file - i always would. Maybe also just point to it from the `README.md` under `Changelog` `[Changelog](./CHANGELOG)`

- Using Github releases. I think this is not practical when looking at how you work and how conan packaging works right now. The main issue here is, conan does yet not deal with the fact that it needs a "packager version" - we package what ever the source library is versioned, using the exact version, and then reupload a "new package build of the same version" using the new hash conan generated when the buildfile changed. I think that is not really compatible / usuable with github releases

I think the best effort would be CHANGELOG, it is used for ages now and would work with most tooling.

For the glibc part: 
In conan-QT, you would mention that you did a major/minor update of glibc, which by default might include breaking changes. So knowing that glibc has been upgraded in the QT changelog will already help. 

Thank you for considering!

**Comment by ericLemanissier** [comment]
you keep mentionning glibc. Are we talking abut https://github.com/bincrafters/conan-glib or https://www.gnu.org/software/libc/ here ?
My point is that such recipe changes happen without any change in the package version, and this cannot be avoided. Some problems (eg cross compiling, build failures etc..) must be solved without waiting for upstream project to release a new version. Some upstream project actually don't release new versions any more.

The solution to communicate changelog has to be compatible with https://github.com/conan-io/conan-center-index/ layout, because at some point the qt recipe will be transferred there (and the vast majority of its requirements are there already). This rules out the github release feature, and makes the CHANGELOG/README.md really cumbersome to use.

**Comment by EugenMayer** [comment]
glib comment comes from https://github.com/bincrafters/conan-glib/commit/3b5a2273d8da7b874973fdd7ea4af3e105c343b1#diff-2b1d42f71f22b7ea0412d7602dec166f

and the issue with that at https://github.com/bincrafters/community/issues/1167#issuecomment-610307554

Very similar to this one, just in this case you updated glib in the qt build, without further notice, which included new changes when build QT - those were hard to find backwards in the end and i hoped that a changelog can at least help finding those earlier or even help to avoid creating issues of things which are not "by design"

I am not sure what `https://github.com/conan-io/conan-center-index/` will mean in terms of a changelog and how it will be included to be displayed there, but use whatever you need for that.

Then create a CHANGELOG.txt in the repo and point to the URL you might be using for the remote, conan-center compatible changelogs - so people find those either way ( just a suggestion )

**Comment by ericLemanissier** [comment]
conan-center-index github repo is great for contributions, but is not really meant to be consulted by users. Accordint to me, a useful changelog(or any piece of documentation) would have to be visible at least in one of these places:

1. https://conan.io/center/zlib/1.2.11/?user=_&channel=_
2. https://bintray.com/conan/conan-center/zlib%3A_#
3 markdown files generated locally
