### ISSUE TITLE
[request] caf/0.18

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#1354]
### Package Details
  * Package Name/Version: **caf/0.18**
  * Changelog: **https://github.com/actor-framework/actor-framework/releases/tag/0.18.0**

The above mentioned version is newly released by the upstream project and not yet available as a recipe. Please add this version.

Is Bincrafters still doing package bumps or is everything going into Conan Center?  Should I add a New Package request for Conan Center instead?  It ought to be there anyway.  I could do the PR for it or at least help with it.

**Comment by Croydon** [comment]
Since CAF has no dependencies it can be migrated to CCI and should be migrated in the mid to long-term. Helping hands to migrate Bincrafters recipe to CCI are very welcome when it is technically possible (no non-migrated dependencies, no system_requirements etc.). When doing that please give clear credits where the recipe is coming from in the pull request description.

Beyond that, we still accept pull requests for all recipes which aren't obviously deprecated (archived git repository).

**Comment by sourcedelica** [comment]
Sounds good.

**Comment by Tarjei400** [comment]
Hey! I adjusted your current recipe in my forked version of conan-caf. It would be nice if maybe we can add that ? 
https://github.com/Tarjei400/conan-caf its on branch testing/0.18.0
I am not sure what is your flow for contributing here. I would appreciate guidence in case I can be more usefull

**Comment by sourcedelica** [comment]
Hi @Tarjei400 -

I am have a PR for a recipe for CAF 0.17.6 and 0.18.0 currently in review at conan-center-index.  It's just about ready to be merged.  Please take a look.   When it's merge it will be available from Conan Center.   I am actually going to close this issue.

**Comment by Tarjei400** [comment]
Ahh perfect, well at least I had exercise then! Cheers!

**Comment by sourcedelica** [comment]
Exercise is healthy! :)  Cheers!
