### ISSUE TITLE
expat/2.2.5 packaged binary - Problem in linking stage

### ISSUE THREAD

**Issue by jgsogo** [bincrafters/community#160]
### Description of Problem, Request, or Question

There is something wrong with binary compiled for gcc 4.9 (x86_64, Release, libcxx=libstdc++11). The error I get in travis when compiling another package that depends on expat is ([here](https://travis-ci.org/jgsogo/conan-apache-apr-util/jobs/349485145)):

```
[100%] Linking CXX executable bin/example
/usr/bin/ld: /home/conan/.conan/data/expat/2.2.5/bincrafters/stable/package/c6d75a933080ca17eb7f076813e7fb21aaa740f2/lib/libexpat.a(xmlparse.c.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
```

If I force compilation of expat/2.2.5 then it works ok ([here](https://travis-ci.org/jgsogo/conan-expat/jobs/349724216)). Maybe it is enough if we generate again all the packages.

### Package Details (Include if Applicable)
* Package Name/Version: **expat/2.2.5**
* Operating System: **Linux**
* Compiler+version: **gcc-4.9**
* Docker image: **lasote/conangcc49**

### Steps to reproduce (Include if Applicable)

Run compilation of [conan-apache-apr-util](https://github.com/jgsogo/conan-apache-apr-util) recipe.

**Comment by SSE4** [comment]
the problem is that lasote has suddenly downgraded image **lasote/conagcc49** from xenial to trusty in this commit: https://github.com/conan-io/conan-docker-tools/commit/60c4f542929580f4bcdbb44b6564db105351c762

that means glibc version was downgraded from 2.23 to 2.19. binaries produced with newer glibc are not backward compatible, as they use new relocations.

that change basically invalidates all packages produced on **lasote/conangcc49** image before today - they all has to be rebuilt.

**Comment by jgsogo** [comment]
So... should it be considered somehow in the hash of the compiled binaries? cc/ @lasote

**Comment by SSE4** [comment]
@jgsogo I've rebuilt expat for gcc-4.9. please give another try.

**Comment by jgsogo** [comment]
It works! Thanks.
