### ISSUE TITLE
Add mingw support to conan-gtest

### ISSUE THREAD

**Issue by sourcedelica** [bincrafters/community#166]
### Package Details (Include if Applicable)
* Package Name/Version: **gtest/1.8.0**
* Operating System: **Windows Mingw**
* Compiler+version: **gcc**

### Steps to reproduce (Include if Applicable)
1. Try to create gtest package using Mingw.
2. Compilation fails with error messages like:
```
[ 12%] Building CXX object source_subfolder/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
In file included from C:/Users/epederson/.conan/data/gtest/1.8.0/bincrafters/stable/build/a8137cc68f43291a51999b4b5805900a416debac/source_subfolder/googletest/include/gtest/internal/gtest-internal.h:40:0,
                 from C:/Users/epederson/.conan/data/gtest/1.8.0/bincrafters/stable/build/a8137cc68f43291a51999b4b5805900a416debac/source_subfolder/googletest/include/gtest/gtest.h:58,
                 from C:/Users/epederson/.conan/data/gtest/1.8.0/bincrafters/stable/build/a8137cc68f43291a51999b4b5805900a416debac/source_subfolder/googletest/src/gtest-all.cc:39:
C:/Users/epederson/.conan/data/gtest/1.8.0/bincrafters/stable/build/a8137cc68f43291a51999b4b5805900a416debac/source_subfolder/googletest/include/gtest/internal/gtest-port.h:1782:3: error: 'AutoHandle' does not name a type
   AutoHandle thread_;
   ^~~~~~~~~~
```

**Comment by dimi309** [comment]
As far as I know this is an "upstream" problem. Gtest v1.8.0 fails compilation with MinGW and the issue has still not been resolved: https://github.com/google/googletest/issues/606

A few days ago I was discussing with @solvingj and I had mentioned that there is a reason to keep gtest v1.7.0 well maintained, because v1.8.0 crashes under some circumstances, but I could not remember what those circumstances are exactly. I have just verified that this is it. Gtest v1.8.0 can't be compiled with MinGW, while gtest v1.7.0 can. If I am wrong, or if someone has additional information, please let us know.

**Comment by sourcedelica** [comment]
Hi Dimi -

I fixed it with https://github.com/bincrafters/conan-gtest/pull/10.

This is based on the answer in https://github.com/google/googletest/issues/606#issuecomment-197933754

**Comment by dimi309** [comment]
I had noticed that's why I deleted my message (sorry). So listen, this all looks good to me now. It's just that I don't have rights to accept the pull request myself. If someone who does can do it, that would be great 😄

**Comment by SSE4** [comment]
@dimi309 seems like PR has been accepted, anything else to be done here?

**Comment by dimi309** [comment]
I don't think so. It looks good to me...

**Comment by SSE4** [comment]
closing out as PR has been accepted. @sourcedelica if you have any other problem(s) with MinGW build of GTest, feel free to open new issue(s).
