### ISSUE TITLE
Proposal: anax

### ISSUE THREAD

**Issue by Nulifier** [bincrafters/community#236]
Here is a recipe for the anax library:
https://github.com/Nulifier/conan-anax/tree/stable/20180319

Appreciate any feedback

**Comment by uilianries** [comment]
Some questions and considerations:

- Looking at https://github.com/miguelmartin75/anax/releases I found the versions 2.x. Why you didn't use tag versions instead of commit hash?
- https://github.com/Nulifier/conan-anax/blob/stable/20180319/conanfile.py#L37 could be removed.
- Just curious, did you try to build on Mingw?
- The test_package looks tiny, I would consider use some [example](https://github.com/miguelmartin75/anax/tree/master/examples) from anax.

Thanks for all your effort!

**Comment by Nulifier** [comment]
Hello,
I wanted to contribute this to Bincrafters. To address your comments:

- I used the commit hash as the last version was from 2015 and there have been major changes since then
- Removed the extra line
- I only built on my computer (VS) and through the travis and appveyor systems
- I fleshed out the test_package somewhat

**Comment by uilianries** [comment]
There are few commits since the version 2.1.0 (less than 20). I would prefer to ask the author to bump the version.  
I'm afraid to use commit as version, because we follow the project releases. WDYT @solvingj ?

**Comment by uilianries** [comment]
Done!

https://github.com/bincrafters/conan-anax/tree/stable/2.1.0
https://github.com/bincrafters/conan-anax/tree/stable/master
