### ISSUE TITLE
[GLEW] FindGlew error

### ISSUE THREAD

**Issue by lucienboillod** [bincrafters/community#241]
### Description of Problem, Request, or Question
Seems to be the same problem than #216 issue.

### Package Details (Include if Applicable)
* Package Name/Version: **glew/2.1.0**
* Operating System: **windows**
* Compiler+version: **Visual Studio 15 2017**

### Reproduce steps
https://github.com/lucienboillod/glew-example

### Solution
We should do the same than Freetype in the FindGlew.cmake in order to set GLEW_LIBRARY variable when called from an third party.

**Comment by dimi309** [comment]
Hi everyone! The external symbols are already in the conan recipe, but you need to add them to your CMakeLists.txt, like this:

`set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${CONAN_EXE_LINKER_FLAGS}")`

**Comment by lucienboillod** [comment]
It gives me the following error:
```CMake Error at CMakeLists.txt:9 (set_target_properties):
  set_target_properties Can not find target to add properties to: glew_example
```

I understand that you use "find_package_handle_standard_args" to add them, but I'm not sure that's the way to go since we have to set them in our CMakeLists.txt and we don't want to modify CMakeLists in some cases like using the package as a thirdparty.

**Comment by dimi309** [comment]
That's strange... It seems that you did indeed name your executable ${PROJECT_NAME}, which is "glew_example". Maybe try to `add_executable(something_hardcoded ... 
`and then `set_target_properties(something_hardcoded ... ` instead of the variable you are using. 

I am not sure I understand how `find_package_handle_standard_args ` harms us here, but if you mean that the FindGLEW.cmake file provided by the package should also link to the missing references, I guess it is another approach bincrafters can consider. Nonetheless, `set_target_properties` definitely works and I think you get that error because of some little detail hidden somewhere in the sample project's configuration.

**Comment by lucienboillod** [comment]
Imo if we have to add something in the CMakeLists to fetch some missing references, then we have a problem. For instance, let's say we have a conan package recipe that needs glew as require (so as a thirdparty), then we don't want to modify in any way the CMakeLists since it is generated by conan. 

Your opinion on this @uilianries  ?

**Comment by dimi309** [comment]
You may very well be right. I am not disputing the strategy you propose. I am just saying that we also need the `${CONAN_EXE_LINKER_FLAGS}` to be up to date and ready to be used with `set_target_properties`, because there is no other way to do it when people don't use Find*.cmake modules and just link to `CONAN_LIBS`. 
Also, as far as I know, when we link *statically* to libraries we have to also link to such dependencies. That's not a problem introduced by the conan packaging. I do have to admit that I do not know if it is general practice to add such link flags in the Find*.cmake modules but I remember, before using conan, that if I wanted to link to glew without using its .dll or .so files, I had to also do a -lgl etc in my makefile or build command line.

**Comment by lucienboillod** [comment]
We can aswell use Find*.cmake but also export symbols as they did with the #216 issue no ?

In the state, the problem is that the package is not usable as thirdparty, which is mainly the use of such package imo. Or maybe there is something I missing in the solution you are proposing

**Comment by dimi309** [comment]
Sure, we can have both. But if someone could introduce a pull request to bincrafters with the needed changes that would be great because I don't have much time these days. You can find all the information about the needed libraries in the conanfile.

**Comment by SSE4** [comment]
I'll take a look at this

**Comment by SSE4** [comment]
@lucienboillod 
I've updated glew and glfw packages with required changes. could you please give a try?
note that the following changes are needed in your example repository:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 11f770f..e0a85d4 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,10 +6,12 @@ set(CMAKE_VERBOSE_MAKEFILE TRUE)
 include(conanbuildinfo.cmake)
 conan_basic_setup()

-find_package(Glew REQUIRED)
+find_package(GLEW REQUIRED)
+find_package(GLFW REQUIRED)
+find_package(Threads REQUIRED)

 add_executable(${PROJECT_NAME} example.cc)
-target_link_libraries(${PROJECT_NAME} ${GLEW_LIBRARY})
+target_link_libraries(${PROJECT_NAME} ${GLEW_LIBRARY} ${GLFW_LIBRARY} Threads::Threads)

 install(TARGETS ${PROJECT_NAME}
         RUNTIME DESTINATION bin
diff --git a/conanfile.py b/conanfile.py
index 0bd2f8d..222bd15 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -12,7 +12,7 @@ class ExampleConan(ConanFile):
     exports_sources = ["CMakeLists.txt", "example.cc"]
     generators = 'cmake'
     settings = "os", "arch", "compiler", "build_type"
-    requires = "glew/2.1.0@bincrafters/stable"
+    requires = "glew/2.1.0@bincrafters/stable", "glfw/3.2.1@bincrafters/stable"

     def build(self):
         cmake = CMake(self)

```

**Comment by lucienboillod** [comment]
Sorry for the delay, I'll test it today

**Comment by lucienboillod** [comment]
Very nice! tested locally and it is working, good job.
Also can you export the package on bintray (both glew and glfw), and if you have some times, there is still Qt/5.9 and freetype to upload on bintray
