### ISSUE TITLE
modular boost - disable individual components (e.g. python)

### ISSUE THREAD

**Issue by SSE4** [bincrafters/community#258]
many slack users are requesting feature to disable individual boost components, mostly boost-python.
b2 itself has neat feature - `--without-<package>` and `--with-<package>`.
although implementation on b2 level is trivial, for our conan packages it might be hard to manage - e.g. dependency tree should be changed on fly considering --with/--without options.
special challenge is circular dependencies (boost has few of them).
additional challenge - probably with/without options also should be smartly applied to package id, likely --without-thread should has no effect on package id of boost.asio, for instance.

**Comment by chrahunt** [comment]
I think my use case is related. I'm using `boost_log` which depends on `boost_parameters` which depends on `boost_python`. `libpython` was not resolved properly by the linker but the latter dependency is only needed at all if using the python-related headers in `boost_parameters`. I worked around it using

```
set_property(TARGET CONAN_PKG::boost_python PROPERTY INTERFACE_LINK_LIBRARIES "")
```

in my project's `CMakeLists.txt`, since there was not a way to remove the requirement from the individual targets.

**Comment by solvingj** [comment]
The python situation was indeed a bad one.  We pushed this issue upstream to boost in 2018.  As of boost 1.69.0, `boost_parameter` no longer depends on `boost_python`.  The bindings for `python` have been moved to a separate library `boost_parameter_python` which depends on both.  I think this removes the strongest and most relatable argument for this feature. 

In any case, closing this as "won't do" because it's just not something we can support. There's also monolithic boost package in conan center which enables something like this today, albiet with very different tradeoffs.
