### ISSUE TITLE
[Qt] Request to include version 5.6

### ISSUE THREAD

**Issue by canmor** [bincrafters/community#295]
### Description of Problem, Request, or Question
I have many users ask for support to older macOS, which is not support by Qt 5.9 and Qt 5.11, According to documents, following is what these version support for macOS:

Qt 5.11: macOS 10.11 above
Qt 5.9: macOS 10.10 above
Qt 5.6: macOS 10.7 above

I currently have my own fork of your Qt recipe and branch for 5.6, but I do hope you get this officially included. I think it's reasonable to support macOS 10.7 when we release app to end user, and it's not hard to include 5.6, just take a branch and have the version coded, right?

**Comment by lucienboillod** [comment]
@canmor yes totally! just waiting for the last PR to be merged and I will create 5.6 version :blush: 
If you need any other version please tell me. I was only packaging last significant versions because I don't know what are the versions still used, is there exist something like a graphic % to know which versions are still importants for the users ?

**Comment by canmor** [comment]
I'm just new to Qt,

**Comment by canmor** [comment]
I'm new to Qt, so I afraid I can provide you more advice, I just found these page shows the platforms Qt support:

**Comment by lucienboillod** [comment]
Amazing! thank you for taking the time to search.
Well from what I see I also think that 5.6 should be enough for retro-compatibility.

**Comment by ShamanTcler** [comment]
If I may join the party Qt has what they call LTS versions, or long term supported. Currently there are two of those Qt 5.6 and Qt 5.9 (https://www1.qt.io/qt5-9/) 

Qt 5.6 is significant because it does NOT require C++ 11. Therefore it can be built with MSVS 2012/2013.

Qt 5.9 requires MSVS 2015 or better.  

By the way I have a Qt commercial licence but choose to stay with the LGPL version. 

Now often a developer writing plugins for 3'rd party apps is limited to which compiler they can use, to maintain ABI.  

Because of this I encourage using LTS versions of Qt and hope to provide them in every compiler flavor.

I will now pester you with other questions in new "issues". I am learning Conan and am committed to it. I really like bincrafters "out of source" build approach. That way when Conan is deprecated in 20+ years the source is still pristine. (Yes in 35 yrs I have seen a lot come and go  ... remember ADA?)

Regards
Carl
