### ISSUE TITLE
debug packages for libraries on bintray (for Visual Studio)

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#313]
### Description of Problem, Request, or Question
I'm adding `cmake_multi` support for my project to comfort Visual Studio developers.
Some dependencies do not have debug packages available on bintray.

The dependency that is missing, is:
- Qt/5.11@bincrafters/stable

Qt5 is a rather big library.
I want the developers to be freed of the burden of having to rebuild these libs.

Will bincrafters provide debug libraries for these (for Visual Studio at least)?

### Steps to reproduce (Include if Applicable)
```
conan install qt/5.11@bincrafters/stable -s build_type=Debug
```

**Comment by SSE4** [comment]
@madebr I probably missed the point, but ffmpeg is built via CONAN_BUILD_TYPES=Debug, and debug packages should be available on bintray

**Comment by madebr** [comment]
Yeah, I wrongly added ffmpeg to the list. I forgot to add an option what made it not available on bintray.
Qt/5.11 though was not available, and failed to build on my machine.

**Comment by SSE4** [comment]
@madebr sure, got it
@lucienboillod is it feasible to provide debug packages as well?

**Comment by lucienboillod** [comment]
@madebr @SSE4  Hello! I don't know if provide debug is feasible, since Qt is a very big package I am afraid of the lack of available space. Anyway, we are in the middle of some significants changes on the Qt package, it should be release by the end of the week so you might wait until the release to update your recipe (5.11 will be remplaced by 5.11.0). I will try to add Debug at the same time :blush:

**Comment by sinall** [comment]
Please also consider debug packages for boost / cpprestsdk.

**Comment by lucienboillod** [comment]
@madebr I tried to build debug on msvc, unfortunatly we encountered build problems, and we are not the only one to have this kind of behavior:
https://forum.qt.io/topic/91078/qt-5-11-0-static-openssl-linked-build-fails
https://forum.qt.io/topic/91078/qt-5-11-0-static-openssl-linked-build-fails

Do you have any recommendation ? If the problem is on the Qt side we won't be able to provide debug version for now.

**Comment by lucienboillod** [comment]
ok we might found a solution, waiting for the result :smile:
