### ISSUE TITLE
Linking problems with spdlog/0.16.3 regarding fmt dependency

### ISSUE THREAD

**Issue by darcamo** [bincrafters/community#321]
### Description of Problem, Request, or Question

I get linking problems related to fmt library, which is a dependency of spdlog.
If I set "spdlog:fmt_external=False" in the options section of my conanfile.txt everything works correctly.

If I use spdlog/0.14.0@bincrafters/stable the problem does not happens. Comparing the recipes from both versions I could see that in 0.16.3 the default value of fmt_external was changed to true. Note that fmt is correctly installed (I can see it with 'conan search'), but from the recipe of the fmt library in my local cache there is an option "header_only" we is set to False by default.

I imagine that the spdlog recipe needs to either set the header_only option of the fmt to True or indicate that it should link with fmt (maybe in spdlog recipe package_info).

Disclaimer: I'm new to conan and I don't have much experience creating recipes yet.

### Package Details (Include if Applicable)
* Package Name/Version: **spdlog/0.16.3**
* Operating System: **Arch Linux*
* Compiler+version: **gcc-8.1.1**
* Docker image: **NA**

### Steps to reproduce (Include if Applicable)
Add spdlog/0.16.3@bincrafters/stable to conanfile.txt
Run "conan install .. --build=missing"

**Comment by uilianries** [comment]
Hi @darcamo !

I'll take a look on this soon.

Thanks for report

**Comment by uilianries** [comment]
spdlog is totally header-only, so there is no heade_only option for it.

fmt could be header_only, but the default is False, as you said.

If you are getting linkage errors, I would suppose that you have some ABI incomparability, because fmt was built under Ubuntu and you are using Arch. Both systems could use different libc and libstdc++. So I recommend to force build libfmt on your system or use both are header-only:

To build all stuff, including fmt:
`conan install spdlog/0.16.3@bincrafters/stable --build` 

To use both as header-only:
`conan install spdlog/0.16.3@bincrafters/stable -o fmt:header_only=True`

**Comment by uilianries** [comment]
UPDATE:

I just updated the package to have spdlog/0.17.0

**Comment by SSE4** [comment]
@darcamo could you possibly upload more verbose log with linking errors you're getting?

**Comment by darcamo** [comment]
Everything works now.
I don't have problems anymore. I just updated my conanfile to use version 0.17.0.

I'm closing the issue now.
Just in case, I'll clone the recipe and try to build it using two different docker containers I use for my own recipes. I'll reopen the issue if the problem occur in a container and put the log here.

ps: I cleaned my cache before running conan install just in case.
