### ISSUE TITLE
Missing cpprestsdk/2.9.1@bincrafters/stable files.

### ISSUE THREAD

**Issue by StiventoUser** [bincrafters/community#322]
### Description of Problem, Request, or Question

Recently I've encountered the error :

```
cpprestsdk/2.9.1@bincrafters/stable: Trying with 'bincrafters'...
ERROR: Request for path: bincrafters/cpprestsdk/2.9.1/stable/export Not Found. [Remote: bincrafters]
```

And it seems that there is no files at https://bintray.com/bincrafters/public-conan/cpprestsdk%3Abincrafters/2.9.1%3Astable#files

### Package Details (Include if Applicable)
* Package Name/Version: **cpprestsdk/2.9.1@bincrafters/stable**
* Operating System: **Windows 10**
* Compiler+version: **VS 14 2015**

### Steps to reproduce (Include if Applicable)

`conan install cpprestsdk/2.9.1@bincrafters/stable -s build_type=Debug -s compiler="Visual Studio"  -s compiler.runtime=MTd -s compiler.version=14 -s os=Windows`

**Comment by SSE4** [comment]
@StiventoUser would you mind update to 2.10.1 or 2.10.2?

**Comment by StiventoUser** [comment]
Looks like 2.10.2 builds and doesn't cause any conflicts with different packages, so there is no problem.
BTW, Is 2.9.1 deprecated?

**Comment by SSE4** [comment]
we were running out of space on bintray, so I've removed some of older versions in order to get some free space. our package 2.9.1 wasn't updated for a long time anyway, while 2.10.1/2.10.2 have new important fixes requested by other users.
if 2.9.1 is absolutely needed, I think I can rebuild it so it's available again, but I'd like to avoid it, unless it's really unavoidable.

**Comment by StiventoUser** [comment]
Ok, thank you for clarification.
I think there is no need due to it works on newer versions.

**Comment by SSE4** [comment]
thanks, I am closing the issue then
