### ISSUE TITLE
qt/5.11.0@bincrafters/stable misses dependencies

### ISSUE THREAD

**Issue by madebr** [bincrafters/community#352]
### Description of Problem, Request, or Question
Linking to `qt/5.11.0@bincrafters/stable` with `-o qt:shared=False` causes the linker to have some missing symbols.

### Package Details (Include if Applicable)
* Package Name/Version: **qt/5.11.0**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2017**

### Steps to reproduce (Include if Applicable)
AppVeyor output: https://ci.appveyor.com/project/madebr/openrw/build/1.0.626

It misses the following dependencies (as far as I understand)
- harfbuzz
- libpng (libpng12?)
- pcre2

I include the `conanbuildinfo.cmake` file and link to qt5 using:
```
set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)

find_package(Qt5OpenGL REQUIRED)
find_package(Qt5Widgets REQUIRED)

target_link_libraries(<target>
    PRIVATE
        Qt5::OpenGL
        Qt5::Widgets
    )
```

**Comment by ericLemanissier** [comment]
What generator are you using?
Currently with cmake only find_package should work. The other solution is to call qmake+nmake/jom.

**Comment by madebr** [comment]
We are using the cmake generator.
The qt application is just a side viewer application, so we want to keep it cmake.

conanfile: https://github.com/madebr/openrw/blob/conan/conanfile.py
CMakeLists.txt of the qt application: https://github.com/madebr/openrw/blob/conan/rwviewer/CMakeLists.txt

**Comment by ericLemanissier** [comment]
https://github.com/madebr/openrw/blob/conan/conanfile.py#L43 please use 5.11.0

**Comment by ericLemanissier** [comment]
Ok, I just realized that I faced the exact same bug yesterday, and it is a known problem when using static build of Qt with cmake  : https://bugreports.qt.io/browse/QTBUG-38913
I'm not confident adding these libs to the recipe, because we don't know in which configuration they are really required. Is it possible for you to add them to you cmakelist or conanfile.py ?

**Comment by madebr** [comment]
Adding that perl script is a bit out of scope. I will look into bundling the qt5 dll's.

**Comment by madebr** [comment]
Btw, the build_requirements are not valid on Fedora Linux.

**Comment by ericLemanissier** [comment]
you don't need a perl script, you can simply add the missing libraries directly in your cmake file with 
target_link_libraries, but I cannot recommend you enough going for a shared build instead. http://doc.qt.io/qt-5/windows-deployment.html will probably help you with the bundling.

build_requirements are probably ok only on ubuntu, because it is the only distribution available for continuous integration on travis with conan package tools. All the other distributions have to be manually tested. We should probably try with Windows Subsystem for Linux.

Anyway, thanks a lot for the report(s) !

**Comment by madebr** [comment]
I currently cannot build conan-qt5 on my Fedora machine because I require `Qt5:opengl=desktop`.

**Comment by ericLemanissier** [comment]
Ok, I found some "official" documentation about fedora requirements : http://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/xcb/README?h=5.11.0 I'll integrate it in the recipe. Thanks again !

**Comment by ericLemanissier** [comment]
Could you please try with the current recipe on my repo https://github.com/ericLemanissier/conan-qt ?

**Comment by madebr** [comment]
@ericLemanissier : The install step of your recipe works. I haven't attempted to download the sources or build it.

**Comment by ericLemanissier** [comment]
The system requirements issue should be solved with latest Qt/5.11.1@bincrafters/stable.
The fix is waiting for merge in 5.6.3 and 5.9.6 branches

**Comment by lucienboillod** [comment]
Changes were pushed. Thanks everyone!

**Comment by ArekPiekarz** [comment]
I'm a little confused how this issue is fixed, because I'm still getting "undefined references" to pthread, pcre2 and some other libs when linking to static Qt. Is the final conclusion not to use static Qt until the upstream issue is fixed?

**Comment by ericLemanissier** [comment]
There are several issues here: what was solved is the Fedora system requirements issue.
The static build linking issue when using cmake is not solved, because it is not an issue with the conan recipe, but from upstream Qt https://bugreports.qt.io/browse/QTBUG-38913
In the meantime you can either switch to qmake, or try to add the missing libs in you cmakelists
