### ISSUE TITLE
Qt shared=False doesn't work due to upstream issue

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#444]
While Qt shared=False seems to be fine with GCC but with Clang 5 it is missing references:

> /home/travis/.conan/data/Qt/5.11.1/bincrafters/stable/package/a004e7be8375368cebf6a1b4fb5003aeac1d5a55/lib/libQt5Gui.so.5.11.1: undefined reference to `inflateValidate@ZLIB_1.2.9'
/home/travis/.conan/data/Qt/5.11.1/bincrafters/stable/package/a004e7be8375368cebf6a1b4fb5003aeac1d5a55/lib/libQt5Core.so.5.11.1: undefined reference to `getentropy@GLIBC_2.25'
clang-5.0:error:linker command failed with exit code 1 (use -v to see invocation)

https://travis-ci.org/Croydon/doxygen/jobs/429346687#L1823

**Comment by ericLemanissier** [comment]
I think you are hitting https://bugreports.qt.io/browse/QTBUG-38913
You are trying to use static Qt from cmake right ?

**Comment by Croydon** [comment]
Exactly. oddly with GCC instead of Clang in the same setup it works work the static Qt version. Only Clang + Qt static (+ CMake?) seems to fail.

**Comment by ericLemanissier** [comment]
It's surprising. The bug I have in mind is between cmake and static Qt, so it should be the same for all compilers. It should disappear by switching to qmake or using shared Qt

**Comment by Croydon** [comment]
Does the recipe a complete from scratch build or does it use some prebuild binaries?

**Comment by SSE4** [comment]
getentropy is provided by libc itself. @Croydon what is GLibc version and Linux distro version on your build machine?

**Comment by Croydon** [comment]
So the very initial problem I did encounter:
I did assume that shared=False is default, like it is common across all recipes

Second, I assumed that the recipe name is lower case as it is common as well. So I used qt:shared=False which is completely effectless.

Now I'm actually using static builds, but still encounter undefined references:
https://travis-ci.org/Croydon/doxygen/jobs/429973629#L1384

pthread doesn't seems to get linked, together with a lot of other stuff.


To solve problem 1 and 2 I would suggest to rename `Qt` to `qt` and make `shared=False` default.

**Comment by ericLemanissier** [comment]
Ok, so now you are truly hitting https://bugreports.qt.io/browse/QTBUG-38913, because you are using static qt from cmake.
I am strongly against making shared=False the default, for 3 reason:
1. Qt's default configuration is shared, not static http://code.qt.io/cgit/qt/qtbase.git/tree/config_help.txt#n105
2. I keep hearing Qt guys advising shared library
3. using static build of qt from cmake is broken https://bugreports.qt.io/browse/QTBUG-38913

**Comment by Croydon** [comment]
shared makes the binary packages pretty much unusable as it's is too unreliable to hope to have to exact same library versions. 🤔

**Comment by ericLemanissier** [comment]
Yes, the safest option is to distribute all the libraries with the executable, as explained http://doc.qt.io/qt-5/linux-deployment.html#shared-libraries
It's a shame that static Qt does not work out of the box with cmake. You can work around the issue by adding the missing libraries to the linker of doxywizard. looking at your travis error, that would be pthread, pcre2, harfbuzz, zlib and libpng

**Comment by Croydon** [comment]
This should probably be added to the package_info() in the qt recipe from my understanding?

**Comment by ericLemanissier** [comment]
Considering that this bug was reported 4 years ago to Qt, I assume that the fix is not trivial, or they would have already updated their cmake files to add the missing libraries. Anyway, trivial or not the bug must be solved upstream. We cannot be sure a priori that these libraries are needed on all platforms, and I don't know if other libraries should be added if other modules of Qt are built. Also, Qt has nearly 200 cmake files for application linking to Qt, so I'm not very inclined to duplicate all this logic in the conan recipe.

**Comment by ericLemanissier** [comment]
this is solved since qt 5.14.0, now that https://bugreports.qt.io/browse/QTBUG-38913 is fixed
