### ISSUE TITLE
Update all CI scripts 

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#482]
### Description of Problem, Request, or Question

Hi!

Conan 1.8.0 came with some structural changes, including Docker images.

Lasote changed all docker image names to `conanio/<compiler><version>`

We need some script to update ALL our travis recipes! It's important because lasote's images will not be updated.

**Comment by Croydon** [comment]
This should be combined to update:
  * adding Clang 7
  * adding apple-clang 10 
  * renaming .travis/ -> .ci/ 
    * the directory plus the references in .travis.yml 
   * (maybe more I'm not thinking about right now)

**Comment by Croydon** [comment]
Excellent work!

If we want to include Clang 7 then we still need to wait until this discussion around the version schema is solved upstream (which I would prefer, otherwise we would have mass updates soon again). https://github.com/conan-io/conan/pull/3643

Maybe until then we also made progress with the Python 2 -> 3 upgrades everywhere (not just in the docker containers) https://github.com/conan-io/conan-docker-tools/issues/53
We could deal with eventual failures because of that across all packages at once then

The only downside I'm seeing in this script: That's now the fourth (or so) place where we have fragments of our templates which needs to be kept up to date.

How is it handling the situation if old compilers are removed because they are unsupported by the project? Are the getting re-added? Would it be complicated to read the latest existing compiler versions from the current CI config files and only add newer ones?

**Comment by Croydon** [comment]
And how complicated is it to update the default_options to a dict? 🤔

**Comment by uilianries** [comment]
> Would it be complicated to read the latest existing compiler versions from the current CI config files and only add newer ones?

That's exactly what I did. I read Travis file, list all compilers and their version, and merge with newest compilers list.

**Comment by uilianries** [comment]
> If we want to include Clang 7 then we still need to wait until this discussion around the version schema is solved upstream (which I would prefer, otherwise we would have mass updates soon again). conan-io/conan#3643

That's true. Maybe we could remove clang 7 for now and add only when finished by discussion.

**Comment by SSE4** [comment]
so far, summary of changes to be made:

- add Apple Clang 10.0
- add Clang 7 (wait for https://github.com/conan-io/conan/pull/3643)
- rename `.travis` to `.ci`
- update docker image names from `lasote/conan<compiler>` to `conanio/<compiler>`
- update python version to `3.7.0` (remove useless variables `PYTHON_VERSION` & `PYTHON_ARCH`)
- update ubuntu to xenial
- update default_options to use `dict()`
- update protected methods and properties (e.g. `build_subfolder`, `sources_subfolder`, `configure_cmake`)
- move MSVC/MinGW builds to travis? (???)

**Comment by uilianries** [comment]
To update Python3 on Appveyor we should declare both version and arch AFAIK:

https://github.com/pyinstaller/pyinstaller/blob/develop/appveyor.yml
http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

**Comment by Croydon** [comment]
I'm pretty sure, yes 

https://github.com/bincrafters/conan-templates/pull/37

**Comment by uilianries** [comment]
I update Bincrafters Conventions ... but I'm waiting for CI

the script looks dirty and a bit complex but works! :face_with_head_bandage: 

- [X] Apple Clang 10.0
- [x] add Clang 7 (wait for conan-io/conan#3643)
- [x] rename .travis to .ci
- [x] update docker image names from lasote/conan<compiler> to conanio/<compiler>
- [x] update python version to 3.7.0 (remove useless variables PYTHON_VERSION & PYTHON_ARCH)
- [x] update ubuntu to xenial
- [x] update default_options to use dict()
- [x] update protected methods and properties (e.g. build_subfolder, sources_subfolder, configure_cmake)
- [x] support conan ci pages

**Comment by Croydon** [comment]
Maybe @SSE4 has already implemented this in the meantime, but it should also remove the sudo: required line altogether in Travis. Using the docker service implicits sudo: true and sudo disable environments are soon getting removed altogether from Travis.

**Comment by Croydon** [comment]
bincrafters-conventions is removing all jobs with something like `CONAN_ARCHS=x86 CONAN_DOCKER_32_IMAGES=1`

**Comment by SSE4** [comment]
I believe it's safe to close now. with https://github.com/bincrafters/bincrafters-conventions/pull/6 we can update all recipes without losing jobs.
