### ISSUE TITLE
Qt 5.11.2 MySQL Error unknown type mybool

### ISSUE THREAD

**Issue by melMass** [bincrafters/community#530]
Hi,

On mac the `Qt/5.11.2@bincrafters/stable` fails:
> Qt/5.11.2/bincrafters/stable/source/qt5/qtbase/src/plugins/sqldrivers/mysql/qsql_mysql.cpp:235:9: error: 
      unknown type name 'my_bool'
        my_bool nullIndicator;

 I think the reason  is related to https://github.com/Homebrew/homebrew-core/issues/29013:
> my_bool was renamed to bool in MySQL 8, and it looks like Qt 5.11 is still targeting MySQL 5.7.

Do you know how to properly report issues like that ?

**Comment by ericLemanissier** [comment]
This is actually a Qt issue, which is solved with https://github.com/qt/qtbase/commit/82b4c79fb90c1a01165b96455ae48715c3059bbe. The fix will be included in Qt 5.12.0, which should be available at the end of the month according to https://wiki.qt.io/Qt_5.12_Release (with a slight delay for the conan package)

**Comment by melMass** [comment]
Thanks, what do you suggest for now then ? Which recipe isn't affected by this.

**Comment by ericLemanissier** [comment]
all recipes are affected by this, because all released qt versions are affected by this. If you don't want to get affected by this bug you can either:
- fork the recipe and make it patch qt sources before build
- disable mysql by using the recipe option config=-no-sql-mysql
- downgrade mysql to a version supported by Qt
- wait for Qt 5.12.0

**Comment by melMass** [comment]
@ericLemanissier Thanks for the quick replies. I'll fork and patch for now and upgrade once 5.12 is released then.
