### ISSUE TITLE
SDL2 and libalsa

### ISSUE THREAD

**Issue by ericLemanissier** [bincrafters/community#629]
SDL2 has an `alsa` option, which triggers the installation of system package libasound2-dev https://github.com/bincrafters/conan-sdl2/blob/stable/2.0.9/conanfile.py#L91. Wouldn't it better if instead it added `libalsa/1.1.5@bincrafters/stable` to the requirements ?

**Comment by uilianries** [comment]
Sounds good, but we need to check with sdl2 users first, otherwise we could break someone maybe.

/cc @sixten-hilborn @madebr @SSE4

**Comment by Croydon** [comment]
> libalsa/1.1.5@bincrafters/stable

We don't have such a package?

**Comment by ericLemanissier** [comment]
Yes we have

**Comment by Croydon** [comment]
Can you please provide a link?

**Comment by Croydon** [comment]
https://github.com/bincrafters/conan-libalsa doesn't exists and neither does https://bintray.com/bincrafters/public-conan/libalsa%3Abincrafters

**Comment by ericLemanissier** [comment]
Woops, I was thinking of https://github.com/conan-community/conan-libalsa actually

**Comment by madebr** [comment]
- Would every user of SDL2 with alsa support then have to provide either a custom `alsa.conf`, `ALSA_CONFIG_PATH` or `ALSA_CONFIG_DIR` environment variable?
The `alsa.conf` of my system (at `/usr/share/alsa/alsa.conf`) is quite complicated.
- Isn't alsa a bit too low level? I mean, you can go as low as create a conan package for the linux kernel and create a new distribution.

**Comment by Croydon** [comment]
> Isn't alsa a bit too low level? I mean, you can go as low as creating a conan package for the linux kernel and create a new distribution.

That is maybe a point we need to talk about.

**Comment by sixten-hilborn** [comment]
What about moving `system_requirements()` for alsa to something like `libalsa/system@bincrafters/stable` ? That avoids breaking the SDL2 package, but it would still allow consumers to override it with `libalsa/1.1.5@conan/stable` if needed.

**Comment by solvingj** [comment]
This particular issue seems basically closed, although it was a good discussion.  However, metapackages for `system_requirements` is an interesting idea for future cases. Would be nice to include them in profiles like `build_requirements`.  Actually, now that I've typed that, it seems to me like a very attractive way to implement them. If anyone agrees , maybe we can create a feature request issue on Conan.

Regarding the broader topic of `system_requires`, I didn't see anybody mention the environment variable: `CONAN_DISABLE_SYSREQUIRES` which we got last year. This alleviates some of the concern around existing cases where `system_requirements` is used, but I definitely agree we should generally leave `system_requirements` out in the future, and only include them after a team discussion where multiple people agree the exception is warranted. 

https://github.com/conan-io/conan/issues/2332

**Comment by SSE4** [comment]
the plan is to switch all dependencies to conan's instead of SystemRequirements.
SystemRequirements have the following troubles:

- scalability issues

1. there are many package managers, and we have to add numerous `if` blocks to support them (`apt`, `emerge`, `yum`, `pacman`, etc.)
2. there are many architectures, and we have to maintain inner `if` blocks for them as well (x86, ARM, PowerPC, etc.)
3. even within same package manager, package names differ from distro to distro (e.g. `Fedora`, `RHEL` and `CentOS` may differ in package names, although  all are `yum` based)
4. even within same distro, package names may differ (e.g. between Ubuntu 12 and 18)

- usability issues

1. system requirements require additional permissions, which might not be available
2. system is polluted with lots of packages
3. conan install may require an interactive session
4. sometimes packages conflict with each other, e.g. on apt you cannot easily install some `i386` and `amd64` packages simultaneously
5. problems with cross-building set ups, especially Windows -> Linux, Mac -> Linux

so, the ultimate goal is to move all SDL2 dependencies to the conan packages. however, many of them need X11, which has very deep dependency tree (I think about 20-30 of various small libraries, to name a few `libX11`, `libXau`, `libXcb`, etc).

for now, I think we may close an issue, as question is answered - SDL2 and others will move from system requirements to conan packages in next couple of weeks.
