### ISSUE TITLE
Add Windows build to conan-gmp

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#65]
It looks like our conan package for GMP does not have appveyor/windows builds.  However, here is an example of a GMP recipe which does.  Perhaps we can learn from that and add windows: 

https://github.com/DEGoodmanWilson/conan-gmp/blob/master/conanfile.py

**Comment by dimi309** [comment]
He's executing configure & make on Windows too:

```
configure_command = "cd %s && %s ./configure --enable-static --enable-shared %s" % (self.ZIP_FOLDER_NAME, self.generic_env_configure_vars(), config_options_string)
        self.output.warn(configure_command)
        self.run(configure_command)
self.run("cd %s && make" % self.ZIP_FOLDER_NAME)
```
So it seems to me that when he says windows he means an msys or cygwin build, which is great but I don't think it solves our problem. The issue here is that the main gmp repository does not provide a classic Windows build (VS or cmake) and the developers just let you set it up yourself if you really need one. On their page, they say:

> GMP's main target platforms are Unix-type systems, such as GNU/Linux, Solaris, HP-UX, Mac OS X/Darwin, BSD, AIX, etc. It also is known to work on Windows in both 32-bit and 64-bit mode. 

The cgal team, (cgal uses gmp) provide a binary of gmp themselves for building cgal. So it seems that there is no ready made procedure to get this done and will take quite a bit of tinkering...

**Comment by dimi309** [comment]
I have looked into compiling GMP on Windows in the past and now I have also looked into the above mentioned implementation. I'm afraid that we still don't have a solution.

First of all, to my understanding, Windows compilations of GMP are not directly supported by the maintainer. From the [GMP project page](https://gmplib.org/):

> GMP's main target platforms are Unix-type systems, such as GNU/Linux, Solaris, HP-UX, Mac OS X/Darwin, BSD, AIX, etc. It also is known to work on Windows in both 32-bit and 64-bit mode.

Upon examination of the GMP project repository, I have seen that there is no Windows compilation support incorporated into the build configuration. Only an autotools build is provided which, out of the box, works on Linux and MacOS, but not Windows. This is not to say that GMP cannot be compiled on Windows. Perhaps it is possible to do that with MSYS or Cygwin, but building against Visual Studio, which is what we need on a first stage in my humble opinion, or with vanilla MinGW Makefiles, is not doable "out of the box".

Initially, we looked into the GMP library because it is a prerequisite for the CGAL library. While looking into CGAL, I have found a further indication that compiling GMP on Windows is tricky. From the [CGAL documentation](https://doc.cgal.org/latest/Manual/installation.html#thirdpartyMPFR):

> As Visual C++ is not properly supported by the Gmp and Mpfr projects, we provide precompiled versions of Gmp and Mpfr, which can be downloaded with the installer CGAL-4.11-Setup.exe.

As far as Don's package mentioned above is concerned, taking a look at the conanfile reveals that it only builds with `configure `and `make`, even though it does some preparatory setup under a "Visual Studio" case in the code. I do not know if it would work with some prerequisites set up but I get this error, as foreseen, when trying to run it on my Windows machine:

```
'make' is not recognized as an internal or external command,
operable program or batch file.
```
I mentioned to @solvingj the other day that I may be lacking some knowledge about how to use autotools with Visual Studio, since  I had heard of some developers actually having done so. But a little research I have performed revealed [discouraging information](https://stackoverflow.com/questions/314553/how-to-use-makefiles-in-visual-studio) for the most part.

In any case, I have also [asked the developer](https://github.com/DEGoodmanWilson/conan-gmp/issues/2) of the above mentioned package if the Windows build has ever worked. There is no answer at the time of writing.

Perhaps the best thing to do is to maintain the position that the GMP package does not support Windows builds because the GMP library does not do so either. When compiling CGAL on Windows, we could work out a trick perhaps to download the proposed GMP binary, or list it as a requirement for deploying the package on Windows.

**Comment by solvingj** [comment]
Thank you very much for doing such thorough research and providing such a great summary!  Sounds like the case can be closed for now. Great work.

**Comment by kheaactua** [comment]
In case any one is interested, I have a conan recipe for GMP 6 that builds with mingw (following the cross-compilation tutorial) and uses a `package_id()` to make it appear as a Visual Studio 2013 (MSVC 12) build.  I haven't posted it on github yet (I'm still tweaking it now and then), but it builds, and I could share it if anyone needs.

**Comment by solvingj** [comment]
Would be great, let us know when you feel comfortable sharing.  You can chat with us about it on slack as well.

**Comment by kheaactua** [comment]
Will do.  Once I finally get CGAL built to confirm it works. :)  (building on Windows is just so slow and tedious)

**Comment by kheaactua** [comment]
Hi @solvingj, I published my GMP and MPFR recipe's to [conan-gmp](https://github.com/kheaactua/conan-gmp) and [conan-mpfr](https://github.com/kheaactua/conan-mpfr) respecitvely.  I haven't put them on bincrafters yet because I still have no `test_package` yet, and while CGAL builds with these, I haven't thoroughly tested my code that depends on this CGAL build yet,

**Comment by solvingj** [comment]
Should be able to just copy/paste our test package. Not sure. Give it a try.
