### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iskaron** [bincrafters/community#655]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bincrafters/conan-protobuf**

### Question Description
Commit d43d322 in stable/3.6.1 removed building of the protoc compiler by patching the protobuf cmakelists. Any reason for that? Can't that just be another option, perhaps default disabled? I would prepare a pull request for it, if desired.

Thanks,
Oliver

**Comment by uilianries** [comment]
Hi!

We have a note about this package  here:
https://bincrafters.readthedocs.io/en/latest/package_notes/protobuf.html

Just to summarize, you can't cross-compile a project if both protoc and libprotobuf are in the same package. The arch will be the same for both artifacts (e.g. armv7), that means you will try to generate .cc files based on your .proto files, however your host wont be able to run proto since it's incompatible.

If you need protoc, there is the package protoc_installer/3.6.1@bincrafters/stable.

Regards!

**Comment by iskaron** [comment]
Ah right, forgot that. Sorry for the inconvenience, and thanks a lot for the fast answer :)

Regards,
Oliver
