### ISSUE TITLE
[question] threadsafe option for sqlite

### ISSUE THREAD

**Issue by uilianries** [bincrafters/community#709]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sqlite/3.27.2**
  * Operating System+version: **ANY**
  * Compiler+version: **ANY**
  * Conan version: **Conan 1.14.1**
  * Python version: **ANY**

### Question Description

Hi @arnesor!

I would like to know if is really required to set threadsafe=2 when building sqlitecpp:

https://github.com/bincrafters/conan-sqlitecpp/blob/stable/2.3.0/conanfile.py#L27

The recipe sqlite3 uses threadsafe=1 by default, which cause some confusion when allied with slitecpp.

Regards!

/cc @prsolucoes

**Comment by arnesor** [comment]
According to the thread-safety chapter in SQLiteCpp README.md: "But SQLiteC++ does not support the fully thread-safe “Serialized” mode of SQLite, because of the way it shares the underlying SQLite precompiled statement in a custom shared pointer (See the inner class “Statement::Ptr”)."

The serialized mode corresponds to -DSQLITE_THREADSAFE=1 (https://www.sqlite.org/threadsafe.html), and should not be used with SQLiteCpp as I understand it. But SQLiteCpp do support -DSQLITE_THREADSAFE=2 (multi-thread) and -DSQLITE_THREADSAFE=0 (single thread)

Regards!
Arne

**Comment by uilianries** [comment]
@arnesor thanks for your very detailed answer! regards!
