### ISSUE TITLE
Open Discussion Regarding MinGW Builds

### ISSUE THREAD

**Issue by solvingj** [bincrafters/community#80]
This issue is intended to gather feedback from the broader user community about how people use MinGW.  

Currently, Bincrafters is considering trying to add MinGW builds to our standard CI templates.  This is an arduous task, as most of the recipe's we've tested require some adjustments to satisfy MinGW builds.  

If we are to go through this process, we want to make sure we're building the most common MinGW configurations people use.  Currently, the list of MinGW builds we copied from the Conan team is listed here: 
```
4.9@x86_64@seh@posix
4.9@x86_64@sjlj@posix
4.9@x86@sjlj@posix
4.9@x86@dwarf2@posix

6.3@x86_64@seh@posix
7.1@x86_64@seh@posix
```
Note that Conan package tools will multiply each of these configurations by 4:  
```
Shared/Debug  
Shared/Release 
Static/Debug 
Static/Release
```

Currently, this results in 24 MinGW builds. 

We can add or remove some of these MinGW configurations based on community feedback, but in the end, 24 is likely to be the practical limit for the number of builds we want to do.  

So, if you use Conan, or want to use Conan, and want to have MinGW builds, please place your feedback here in this ticket over the next few weeks.

**Comment by solvingj** [comment]
Additional Note:  If you have experience with Conan and MinGW, and are able to contribute some time, we'd like to chat with you.  You can reach us at https://cpplang.now.sh #bincrafters.

**Comment by ArekPiekarz** [comment]
I think the fastest and pretty reliable way to know how people use it would be to look at what they are getting from some popular MinGW binaries providers. For instance let's take a look at [MinGW-w64](https://sourceforge.net/projects/mingw-w64/files/) project, where on the right you can see statistics of downloads per week.

The most popular downloads are:
1)  [The online installer](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/) at 15,659/week, probably because it is the first item on the list of binaries.
2) [7.2.0 x86 posix dwarf](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/7.2.0/threads-posix/dwarf/) at 12,343/week. I believe it's because it's the default variant when using the online installer.
3) [7.2.0 x86_64 posix seh](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.2.0/threads-posix/seh/) at 8,076/week. It's on the 3rd position on the list of things to download, where the second is sjlj variant. I think at this point people are starting to research the distinction between configurations and choose more wisely.

Now looking at [MinGW](https://sourceforge.net/projects/mingw/) project, they seem to have more users, but older software. The most popular compiler seems to be [GCC 6.3.0 x86](https://sourceforge.net/projects/mingw/files/MinGW/Base/gcc/Version6/gcc-6.3.0/) at 18,960/week, although I can't see any info there about the threading or exceptions model. 

If you want you can try yourself to collect a more complete list. 

As for myself, I'm using GCC x64 from Msys2, which is 7.2.0/POSIX/SEH ;-)

**Comment by solvingj** [comment]
Great feedback!! Thanks so much :)  Will ponder this a bit.

**Comment by SSE4** [comment]
some information that might be helpful https://wiki.qt.io/MinGW-64-bit

**Comment by solvingj** [comment]
Hrmn, also very interesting.  Good find.

**Comment by ArekPiekarz** [comment]
That Qt wiki page explains some topics related to MinGW, but different sections in it have a varying degree of being outdated. For instance they define a "recent compiler" as GCC 4.7.

Right now the latest version of MinGW used in Qt prebuilt binaries is 5.3 x32, They provide a whole toolchain with them, so people use it to build other libraries too. They planned for some time to add or switch to MinGW x64 in Qt 5.11 - see https://bugreports.qt.io/browse/QTBUG-35288 - but I'm not seeing it yet in Qt 5.11 alpha preview in Qt Online Installer. Increasing minimal required GCC version was another orthogonal topic, for which I haven't found a conclusion yet. However they do test the compilation of Qt internally with GCC 7 in their CI - https://bugreports.qt.io/browse/QTQAINFRA-1258.

Also, Msys2 has just updated GCC to 7.3.0 ;-). I'm actually impressed by their speed.

**Comment by theirix** [comment]
Several core packages from conan-center like `zlib` or `OpenSSL` switched to numbering their mingw builds using only major gcc version. Maybe we should switch too? It's needed to check and enforce policies in Conan docs (cannot find it yet).

For example, zlib now have `5@x86_64@seh@posix, 6@x86_64@seh@posix, 7@x86_64@seh@posix` instead of old `6.3@x86_64@seh@posix, 7.1@x86_64@seh@posix"`. Changed at https://github.com/lasote/conan-zlib/commit/65bd883a10b93d499a83dadd63897497bdc62e55#diff-180360612c6b8c4ed830919bbb4dd459

Search gives both old 7.1 and new 7:
```sh
conan search -q 'os=Windows and compiler=gcc' "zlib/1.2.11@conan/stable" -r conan-center
```

**Comment by SSE4** [comment]
using major only GCC versions for MinGW is consistent with current policy for Linux GCC versions. I'd suggest to follow the same policy in our recipes.

**Comment by theirix** [comment]
Checked manually major conan-center packages - boost, zlib, bzip2, openssl. All of them use a major version. All of them use `seh@posix` and none of them use `sjlj` or `dwarf2`.

Our issue #76 is closely related. I think we can split configurations at least for two pages:
-  "standard": ```MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix, 6@x86_64@seh@posix, 7@x86_64@seh@posix"```
- "optional": ```MINGW_CONFIGURATIONS: 4.9@x86_64@sjlj@posix, 4.9@x86@sjlj@posix, 4.9@x86@dwarf2@posix```

I think we can safely switch. I have already for libcurl :) Switching other tracked packages.

**Comment by solvingj** [comment]
Great work, I support

**Comment by SSE4** [comment]
I guess now we have a conclusion, so closing
