### ISSUE TITLE
Where does conan put Qt5Config.cmake?

### ISSUE THREAD

**Issue by tjwrona1992** [bincrafters/community#820]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.2**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2019 Preview**
  * Conan version: **Conan 1.15.1**
  * Python version: **Python 3.7.1**
  * CMake version: **CMake 3.14.4**

### Question Description
I am trying to create a project that uses QtCharts. I added at to my conanfile like so:

    [requires]
    qt/5.12.2@bincrafters/stable
    
    [options]
    qt:qtcharts=True
    
    [generators]
    cmake_paths

    [imports]
    bin, *.dll -> ./bin
    lib, *.dylib -> ./bin

Qt downloads and installs successfully during cmake generation, but when it gets to `find_package` it fails saying it can't find Qt5Config.cmake. I searched all of my ".conan" folders and it looks like that file is nowhere to be found.

Since the package config file seemed to be missing i tried to use a more conan style approach and instead of using `find_package` I tried linking to `CONAN_PKG::qt`, but then it seems to have issues running AUTOMOC so I get a bunch of linker errors when I try to build my code.

Oddly when I link to `CONAN_PKG::qt` it also seems to get the include paths a bit off and I need to include `#include <QtCharts/QLineSeries>` instead of just including `#include <QLineSeries>` which doesn't seem quite right. If anyone knows anything about this issue as well I'd be interested to know why this happens.

So I guess there's 2 questions:

1. How can I get this to find Qt properly so I can use QtCharts in my application?

2. How come linking to `CONAN_PKG:qt` doesn't seem to do things quite right?

(Note: I tried qt/5.12.3, but it failed to install - there is already another ticket open for that but I figured I'd mention it so you knew why I was using version 5.12.2)

**Comment by ericLemanissier** [comment]
The only possible way to consume qt from cmake (and this is independant of the packaging system) is to follow instructions on https://doc.qt.io/qt-5/cmake-manual.html. This is what the test recipe uses, so you can start from here : https://github.com/bincrafters/conan-qt/blob/testing/5.12.3/test_package/CMakeLists.txt
You should not need the cmake_paths generator. Does it solve your problem ?

**Comment by tjwrona1992** [comment]
Hi @ericLemanissier, Thanks for the tips, but I'm still having issues finding it.

I even tried just searching for Qt5Core like the test package does, but I just get an error saying `find_package` failed.

    set(CMAKE_INCLUDE_CURRENT_DIR ON)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTOUIC ON)

    find_package(Qt5Core CONFIG REQUIRED)

Running CMake generation fails:

    1> [CMake]   Could not find a package configuration file provided by "Qt5Core" with any
    1> [CMake]   of the following names:
    1> [CMake] 
    1> [CMake]     Qt5CoreConfig.cmake
    1> [CMake]     qt5core-config.cmake
    1> [CMake] 
    1> [CMake]   Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
    1> [CMake]   "Qt5Core_DIR" to a directory containing one of the above files.  If
    1> [CMake]   "Qt5Core" provides a separate development package or SDK, be sure it has
    1> [CMake]   been installed.

I tried removing the `cmake_paths` generator from my `conanfile.txt` and still end up with the same result.

**Comment by tjwrona1992** [comment]
I don't see any Qt related "Config.cmake" files in any of my `.conan` folders even after conan installs it successfully.

**Comment by ericLemanissier** [comment]
It is normal you don't find any qt file in your .conan directory, because qt recipe uses `short_paths` attribute https://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths. you should go in `.conan\data\qt\5.12.3\bincrafters\stable\package\whatever`, you will find a file named `.conan-link` which contains the path to the actual files. the file `Qt5CoreConfig.cmake` wil be in the subdirectory `lib\cmake\Qt5Core\`
qt recipe appends the proper path to `CMAKE_PREFIX_PATH` environment variable, so you can use `virtualenv` generator, and call `activate` before you try to build your program. It is true that the `cmake_paths` generator should do the same job, did you include the `conan_paths.cmake` generated file as mentionned here https://docs.conan.io/en/latest/integrations/cmake/cmake_paths_generator.html?highlight=cmake_paths#included-as-a-toolchain ?

**Comment by tjwrona1992** [comment]
I did not include `conan_paths.cmake`, after doing that it found it successfully! Thanks!

I will need to look more into the virtualenv way of doing things though that sounds interesting.

**Comment by picolloo** [comment]
@ericLemanisser do you have another link to this reference? this one seems to be missing

**Comment by picolloo** [comment]
I have found this reply that was made last year, does it still happen by now?

>indeed,_ cmake_multi cannot work with Qt, because cmake_multi it is incompatible with find_package, and Qt supports cmake only via find_package.
> For your CMakeLists, you have to use what is described on [Qt doc](http://doc.qt.io/qt-5/cmake-manual.html):
> 
> > find_package(Qt5Core CONFIG REQUIRED)
> > target_link_libraries(${PROJECT_NAME} Qt5::Core)
> 
> as seen on the [test package](https://github.com/bincrafters/conan-qt/blob/stable/5.11.2/test_package/CMakeLists.txt)

**Comment by picolloo** [comment]
I think this issue might be the same as #323, but without cmake_multi. Does this limitation happen to cmake by now?

**Comment by ericLemanissier** [comment]
@picolloo I don't think your problem (happening at cmake time) is related to #323 (happening at link time)
The proper link to the documentation I mentionned in my last message is now https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_paths_generator.html
If after following these instructions, your problem is not solved, please open another issue, and join your conanfile, CMakeLists.txt, the conan and cmake conan you execute, and the logs.

**Comment by picolloo** [comment]
@ericLemanissier it really works, thank you very much, it took me more than I expected to find this solution.
