### ISSUE TITLE
Export PATH for QT

### ISSUE THREAD

**Issue by drozel** [bincrafters/community#864]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.12.4@bincrafters/stable**
  * Operating System+version: **Linux Ubuntu 19.04**
  * Compiler+version: **gcc-8.3**
  * Conan version: **Conan 1.16.1**
  * Python version: **Python 3.7.3**

### Question Description
I tried to use QT package and it doesn't work as i expect.
I'm not using cmake, i just call qmake on building of my library, that requires qt. The solution worked in my package is to export path to QT in the PATH variable and than call qmake in build() step of my pakage. But in the conanfile of the Bincrafter's QT PATH exported only for windows.. 
Why not enable it for all platforms?

**Comment by ericLemanissier** [comment]
The line adding bin folder to path environment is a very old remnant. I would actually be more inclined to remove it altogether. In order to call qmake, you can either use the `virtualenv` generator,  or use the `run_environment` argument of `self.run` as in https://github.com/bincrafters/conan-qt/blob/0800cfeca504ea07af96f097e6f8ef225e8bb8e7/test_package/conanfile.py#L49

**Comment by drozel** [comment]
@ericLemanissier yes, it works! Thank you
