### ISSUE TITLE
[GMP] allow building GMP with c++ support

### ISSUE THREAD

**Issue by weatherhead99** [bincrafters/community#888]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **GMP/6.1.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc-7.4.0**
  * Conan version: **Conan 1.16.0**
  * Python version: **Python 3.7.1**

### Description of your feature
The GMP library has optional c++ headers "gmpxx.h" which are necessary for building some downstream things which optionally depend on GMP (notably, the DUNE project numeric libraries). This can be enabled using the --enable-cxx flag on configuring gmp.
I am happy to implement this by adding an extra option to the package as it is very simple, however there is a major complication.
When building with --enable-cxx the library is no longer "pure c". I'm not sure how to handle that in e.g. the build.py script. Would we have to then build GMP as not "pure_c" even when it is? What implications does that have? Or would some more complicated machinery be needed? Or should this be a totally separate package subclassed from GMP with one extra option?

Thanks,
DW

**Comment by SSE4** [comment]
@weatherhead99 let's do the following:
1. add new option like `enable_cxx` or `with_cxx` with default value `True`
2. in recipe, conditionally remove `self.settings.compiler.libcxx` depending on the option above
3. in `build.py` just use `pure_c=False` as we're building with C++ by default
could you prepare such PR?

**Comment by SSE4** [comment]
merged

**Comment by uilianries** [comment]
Thanks @weatherhead99 !

**Comment by stephan-hof** [comment]
Hi, this change causes an issue on my linux machine.
I have the following conan settings:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
```
=> No shared libraries.

The requirements in my conan file looks like this: `gmp/[>=6.1.2]@bincrafters/stable`

Now when it comes to linking the following happens:
```
/bin/bash ../libtool  --tag=CC   --mode=link gcc  -m64 -O3 -s   -version-info 6:1:0 -m64 -L/root/.conan/data/gmp/6.1.2/bincrafters/stable/package/4c8a9fcac580515a995c6103c864b8664dadc528/lib 
-o libmpfr.la -rpath /root/.conan/data/mpfr/4.0.1/ax/stable/package/3194b08e9e72d34d5a9cadb198c967c79cb28859/lib exceptions.lo pool.lo
-lgmp -lgmp -lgmpxx
```

Followed by the following error
```
libtool: error: '/home/conan/.conan/data/gmp/6.1.2/bincrafters/stable/package/4c8a9fcac580515a995c6103c864b8664dadc528/lib/
libgmp.la' is not a valid libtool archive
```

Which is true, because it has been removed here: https://github.com/bincrafters/conan-gmp/blob/stable/6.1.2/conanfile.py#L80

However the file `libgmpxx.la` is still present and referencing the `libgmp.la` => libtool is forced to look for this file but not finding it.

```
cat /root/.conan/data/gmp/6.1.2/bincrafters/stable/package/4c8a9fcac580515a995c6103c864b8664dadc528/lib/libgmpxx.la

dependency_libs=' /home/conan/.conan/data/gmp/6.1.2/bincrafters/stable/package/4c8a9fcac580515a995c6103c864b8664dadc528/lib/libgmp.la'
```

https://bintray.com/bincrafters/public-conan/download_file?file_path=bincrafters%2Fgmp%2F6.1.2%2Fstable%2F0%2Fpackage%2F4c8a9fcac580515a995c6103c864b8664dadc528%2F0%2Fconanmanifest.txt

So my suggestion would be to remove the `libgmpxx.la` as well like its done for `libgmp.la`

**Comment by SSE4** [comment]
yes, we have to remove all libtool files. I'll apply require changes
