### ISSUE TITLE
ImportError when installing websocketpp

### ISSUE THREAD

**Issue by mateiradu** [bincrafters/community#9]
## Description
I was attempting to install my project's sole requirement cpprestsdk which, among other libraries, relies on websocketpp.
The installation process fails when it reaches the point to install websocketpp with an ImportError.

### package
List of relevant packages involved:
- `cpprestsdk/2.9.1@bincrafters/stable`, requires
  - `websocketpp/0.7.0@bincrafters/stable`

### Expected result
Installation of websocketpp to be successful.

### Actual result
The installation process is blocked with the following error message:
```
ERROR: Unable to load conanfile in ****/.conan/data/websocketpp/0.7.0/bincrafters/stable   /export/conanfile.py
  File "****/.conan/data/websocketpp/0.7.0/bincrafters/stable/export/conanfile.py", line 1, in <module>
    from conans import ConanFile, tools, os
ImportError: cannot import name os
```

### Steps to reproduce
- Create `conanfile.txt` in the root of a CMake based project like follows:
  ```
  [requires]
  cpprestsdk/2.9.1@bincrafters/stable

  [generators]
  cmake
  ```
- Configure `CMakeLists.txt` as follows:
  ```
  cmake_minimum_required(VERSION 3.9)
  project(test_cpp)

  set(CMAKE_CXX_STANDARD 11)

  include(build/conanbuildinfo.cmake)
  conan_basic_setup()

  add_executable(test_cpp test.cpp)

  target_link_libraries(test_cpp ${CONAN_LIBS})
  ```
- `mkdir build && cd build && conan install ..`
- Observe the console until it reaches the point to process websocketpp and fail.

### Extra information
I found this [conan-gsl_microsoft PR](https://github.com/bincrafters/conan-gsl_microsoft/pull/1) addressing a similar issue. I was able to successfully install websocketpp by manually editing my local `****/.conan/data/websocketpp/0.7.0/bincrafters/stable/export/conanfile.py` like in the mentioned PR, changing from:
```
from conans import ConanFile, tools, os
```
to:
```
from conans import ConanFile, tools
import os
```

* Conan version: **v0.29.2**
* Operating System: **macOS 10.13.1**
* Compiler+version: **gcc-4.2.1**

**Comment by dimi309** [comment]
Hello!
I've implemented a fix. Since it is not published on bintray yet, could you please try the following and let me know if it works for now? I will then let you know when we have published everything.

```
mkdir temp
cd temp
git clone https://github.com/bincrafters/conan-boost-atomic
cd conan-boost-atomic
git checkout testing/1.64.0
conan create bincrafters/testing
cd ..
git clone conan-boost-system
cd conan-boost-system
git checkout testing/1.64.0
conan create bincrafters/testing
cd ..
git clone https://github.com/bincrafters/conan-websocketpp
cd conan-websocketpp
git checkout testing/0.7.0
conan create bincrafters/stable
```

... and then try your build again. I know that this looks a bit messy but it is only until we publish the fix.

**Comment by mateiradu** [comment]
I'll try it out tomorrow asap and let you know, thanks for the quick reply!

**Comment by mateiradu** [comment]
## Short version
Following the mentioned steps, the package `cpprestsdk/2.9.1@bincrafters/stable` was build successfully and by extend also `websocketpp`.

There have been some unexpected behaviors at some point but maybe they are unexpected just for me that I'm inexperienced with Conan. Nevertheless I preferred to document them below just to be sure 🙂.

## Long version
I tried out the steps and it all goes well until I perform the last step `conan create bincrafters/stable` for websocketpp and of course after switching to `testing/0.7.0`: it complains that some Boost prebuild packages were missing. Some of them were:
- `Boost.Container/1.64.0@bincrafters/testing`
- `Boost.Regex/1.64.0@bincrafters/testing`
- `Boost.Exception/1.64.0@bincrafters/testing`

Conan suggested each time to build them from sources so I thought I can make this quicker using directly `--build missing`. This also means that more packages were missing than the ones mentioned above.

In the end websocketpp was built and I went on to try building my project but I get stuck with a long warning list when I do `conan install`. The list shows WARN messages like the following regarding many Boost related packages:

```
WARN: Conflict in Boost.Core/1.64.0@bincrafters/stable
    Requirement Boost.Config/1.64.0@bincrafters/testing conflicts with already defined Boost.Config/1.64.0@bincrafters/stable
    Keeping Boost.Config/1.64.0@bincrafters/stable
    To change it, override it in your base requirements
```

At first I tried to empty `.conan/data` and repeating the process thinking that my previous build attempts prior to opening this issue installed the stable packages and thus creating the conflicts, but even so the warnings still pop out.

After the long warning list the process goes on installing additional packages. Again I encounter some `ERROR: Missing prebuilt package for 'Boost.[PACKAGE_NAME]/1.64.0@bincrafters/stable'` and so I continue with `--build missing`.

Finally the package that I needed `cpprestsdk/2.9.1@bincrafters/stable` was build successfully and by extension websocketpp 🎉.

**Comment by dimi309** [comment]
Hi @mateiradu. First of all, many thanks for taking the time to explain how the procedure went in detail, so that we can better understand it. 
As far as I know, conan doesn't report all the packages that need building when you are missing a few binaries, but only mentions the ones that are blocking your setup on each run, proposing you to `--build` them one by one. So you did good to use `--build missing`. I use it all the time. I just thought I could foresee 100% how those steps would work on your machine, which wasn't the case (sorry) 😬
If I am not mistaken, the warnings you received are there because deploying the packages the way I have suggested is a bit hacky and leads to packages from the testing and the stable channel to be deployed at the same time. I believe the warnings will go away once my little [websocketpp bug fix](https://github.com/bincrafters/conan-websocketpp/commit/65a2529689957895d252ea1a512711789b995c6d) gets published on bintray and you redeploy your dependencies from there. I will keep you posted on the progress on that.

**Comment by mateiradu** [comment]
I understand, thank you for the explanations 🙂.

**Comment by dimi309** [comment]
You're welcome @mateiradu!

We have published the websocketpp fix. Whenever you have some time, could you clear your cache (basically, delete .conan/data) and try a fresh `conan install` on your project? It should work now. Please let us know how it went.

cc @SSE4

**Comment by mateiradu** [comment]
@dimi309, I was able to do a clean build without any errors and warnings  🎉!

Thanks again for your time and patience.

**Comment by dimi309** [comment]
Wonderful! Thanks for telling us!
