### ISSUE TITLE
[sdl2] problems on linux

### ISSUE THREAD

**Issue by prsolucoes** [bincrafters/community#902]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **sdl2/2.0.9**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-5.4**
  * Docker image: **conanio/gcc7**
  * Conan version: **conan 1.18.0**
  * Python version: **Python 3.7.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

The profile is from travis but the profile used to linux is:
```
include(default)

[settings]
os=Linux
arch=x86_64
```

### Steps to reproduce (Include if Applicable)

Download this sample project and execute the same linux that travis:
https://github.com/ezored/ezored-sdl2

### Logs (Include/Attach if Applicable)

Full log:
https://travis-ci.com/ezored/ezored-sdl2/jobs/223070389#L3705

The strange thing is that old build works, but after change appveyour i found the problem:
https://travis-ci.com/ezored/ezored-sdl2/builds

**Comment by uilianries** [comment]
You are using the same job to build both x86 and x86_64, which requires re-installing  all system dependencies according your target. System requirements are limited as you can see, sometimes it doesn't work well because APT cache or incompatible dependency.

I would recommend splitting your CI job by two, one per arch. Also, you are not using Docker. It's not a real problem, but Travis offers Ubuntu Xenial, which is a bit outdated.
