### ISSUE TITLE
[bincrafters-conventions] Support installer recipes better

### ISSUE THREAD

**Issue by Croydon** [bincrafters/community#932]
Right now, the tools is adding new CI jobs for newer compiler versions which is undesired for installer recipes

**Comment by Croydon** [comment]
Do we have a safe-bet way to detect installer recipes?
We could just look at the name and say every recipe which name ends in `_installer` is one, but we probably have some ancient recipes which don't have this naming schema... 

Should we rename those, create manually a list of those or is there a better way for detection?

@uilianries @SSE4

**Comment by uilianries** [comment]
Good catch @Croydon !

We have two flavors, `_installer` and mixed recipes (e.g. protobuf, flex, bison). Installer recipes are easier to parse because we are using only one recipe, but for mixed recipes, it will be complicated. As we have a base recipe which contains the basic method, we would need to load the recipe (I don't remember if we are doing it right now) and parse as well.

Another option is checking for settings, as we know, installer recipes contain os_build and arch_build.

**Comment by Croydon** [comment]
Hybrids have an own issue: #752 

The build jobs can also be easily detected since they specify the custom conanfile path via env variables

Header-only recipes include `self.info.header_only()`

But installer-only doesn't seem to have any unique thing which can be easily detected 🤔

**Comment by uilianries** [comment]
well, IIRC we manipulate self.env_info.PATH and os_build/arch_buid. But the problem is, if someone implements a wrong recipe, like forgetting some of this points, our script won't detect as an installer. I would say the suffix name for recipe or project, the "_installer" should be enough, WDYT?
