### ISSUE TITLE
Add libuvc

### ISSUE THREAD

**Issue by SalDiAngelus** [bincrafters/community#947]
### Package Details
  * Package Name: **libuvc**
  * Operating Systems+versions: **Linux**
  * Compiler support: **gcc-4.9, gcc-5, gcc-6, gcc-7, clang3.9, clang4, clang5, clang6, clang7**
  * Conan recipe repository: **https://github.com/SalDiAngelus/conan-libuvc**

### Inclusion request
  * Fill all checkboxes with x if you agree with the statement or if it applies to your Conan recipe
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

Right now the supported compilers are limited by built packages for libusb. Should I add --build missing?
I've read though the docs, but I still can't upload from travis to my bintray account. I have bintray set up at https://bintray.com/saldiangelus/libuvc and travis has CONAN_PASSWORD set.

### Checklist for the Bincrafters team
  * Ignore this if you are not part of the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [x] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by uilianries** [comment]
Hi @SalDiAngelus !

Thanks for your contribution, we will review it soon!

**Comment by Croydon** [comment]
Hi @SalDiAngelus!

I have cloned your recipe to https://github.com/bincrafters/conan-libuvc, enabled CI and applied some convention updates, including:
  *  we no longer provide 32-bit builds
  * the libjpeg dependency now uses [the CCI version](https://github.com/conan-io/conan-center-index/tree/master/recipes/libjpeg)
  * the recipe uses now the conandata.yml file instead of the `version` attribute

I have also added the missing compiler builds to libusb

Unfortunately, some of these changes caused that the builds to fail as it can't find the libusb headers anymore 🤔 e.g https://travis-ci.com/bincrafters/conan-libuvc/jobs/240480658#L820

Any idea why?


@SSE4 recently made a commit to libusb which sounds that it should prevent something like this https://github.com/bincrafters/conan-libusb/commit/8f4a3b966c6ad57db20dcdcb4138d92c38b9ee19

________

Please note that due to the `conandata.yml` file the workflow changes slightly, you need now to execute e.g. `conan install libuvc/0.0.6@` to build the recipe

**Comment by SalDiAngelus** [comment]
Thanks for accepting the library! I'm trying to reproduce the failure you're seeing with including libusb.h. Lines 32-33 in conanfile.py are supposed to fix that and I'm able to run `conan create . libuvc/0.0.6@xx/yy` without issues. I'm having trouble with your latest in travis.ci though. Can you check https://travis-ci.com/SalDiAngelus/conan-libuvc/jobs/240503329#L352?

**Comment by Croydon** [comment]
@SalDiAngelus You need to create a `testing/0.0.6` git branch

**Comment by Croydon** [comment]
I have removed macOS builds.
I have also tested it locally on Windows and it fails. I think it is odd that it fails with macOS & Windows as libuvc claims to be cross platform.

Anyway, thanks for your contribution @SalDiAngelus!
