### ISSUE TITLE
[thrift] Question

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [bincrafters/community#951]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **thrift/0.12**
  * Operating System+version: **Windows**
  * Compiler+version: **Visual Studio*
  * Conan version: **Conan 1.17.1**
  * Python version: **Python 3.7.3**

### Question Description
I require both the Thrift installer and the Thrift library as dependencies.

If my colleague runs `conan install thrift/0.12.0@bincrafters/stable` on his Linux machine, he gets both the library as well as the binary in his cache.

On my machine I only get the library. I can then run `conan install thrift_installer/0.12.0@bincrafters/stable` to get another package with the binary.

Did my colleague do some extra steps or is mine just not working? I see the Thrift conan is maintained as separate conan files for each in one repo, but I'm not quite divining how the decision is made on which to install.

**Comment by uilianries** [comment]
Hi @Mirko-von-Leipzig !

Indeed thrift package is divided by two packages, the installer, which contains only the "compiler" and thrift one which contains only the libraries. If your colleague has both libraries and binary installed only by thrift, probably the recipe is outdated.

You can update the recipe by `conan install -r bincrafters -u thrift/0.12.0@bincrafters/stable`. I can say it because thrift package does not requires its installer. Maybe a conanfile.txt was used to install both.

**Comment by Mirko-von-Leipzig** [comment]
Thanks!
