### ISSUE TITLE
mongo-cxx-driver - Consider changing boost dependency to bincrafters modular dependencies

### ISSUE THREAD

**Issue by bmwrightson** [bincrafters/community#955]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: mongo-cxx-driver/3.3.0

### Description of your feature
Currently this package depends on Boost/1.70@conan/stable, given that it is a bincrafters package would it make more sense to use the bincrafters boost modular packages?

Perhaps have 2 versions so that the user can choose one or the other to avoid depending on 2 redundant boost packages, if they already depend on the opposite boost package?

**Comment by bmwrightson** [comment]
Sorry,

I seem to have made a change myself to use the conan version of boost locally, and now I am looking at the bincrafter one and confused myself. It does still beg the question of what to do when some dependencies use one set of boost packages and you want to use the other.

**Comment by Croydon** [comment]
Pretty much all when not absolutely all recipes use the monolithic Boost. One of the biggest reasons is that it is actually in Conan Center and works well. 

To be honest, our modular Boost is outdated, not in Conan Center and has quite some integration problems when it comes to getting consumed by other packages.

This issue here might be something to discuss about in the mind and long term future, but for now it is pretty clear that we will continue to use the monolithic Boost package within other recipes.

Introducing such an option now would not work for most packages (all packages which are in Conan Center), and would cause many conflicts anyway
