### ISSUE TITLE
Question about error conan install with qt

### ISSUE THREAD

**Issue by AurelienFT** [bincrafters/community#965]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.11.2**
  * Operating System+version: **Linux Ubuntu 16.04**
  * Compiler+version: **gcc-7**
  * Docker image: **gcc**
  * Conan version: **Conan 1.18.4**
  * Python version: **Python 2.7.0**

### Question Description
I have run conan install with the following conanfile.txt :
```
[requires]
Qt/5.11.2@bincrafters/stable
opus/1.3.1@bincrafters/stable
portaudio/v190600.20161030@bincrafters/stable
sqlite3/3.29.0@bincrafters/stable
sqlite_orm/1.4@bincrafters/stable

[generators]
cmake
```

The remote to find my `qt` package is : `https://api.bintray.com/conan/bincrafters/public-conan`

And when I run `conan install .` I got the following error :
```
Qt/5.11.2@bincrafters/stable: Configuring sources in /root/.conan/data/Qt/5.11.2/bincrafters/stable/source
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Qt/5.11.2@bincrafters/stable: Error in source() method, line 166
	self.run("wget -qO- %s.tar.xz | tar -xJ " % url)
	ConanException: Error 2 while executing wget -qO- http://download.qt.io/official_releases/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.tar.xz | tar -xJ 
```

If anyone can help me on this error thanks a lot.

**Comment by uilianries** [comment]
Hi @AurelienFT !

Are you able to run manually this command to check the output. Your description is related to download error, but don't know the cause. Maybe server error, outdated certificate, disk free space, write permission ...

**Comment by ericLemanissier** [comment]
This is because qt moved all the old installers to an old URL. it is not http://download.qt.io/official_releases/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.tar.xz, but http://download.qt.io/archive/qt/5.11/5.11.2/single/qt-everywhere-src-5.11.2.tar.xz
5.11.3 has the proper URL (and 5.12.4 and 5.13.1). Can you migrate to a newer version of qt ?

**Comment by uilianries** [comment]
Sure! We also can use a try catch for downloading, like, first try to download using the old url, if an error occurs, then try with new url

**Comment by ericLemanissier** [comment]
Actually, we don't have to use try, because all versions are available in the archive folder. We just did not take the time to update all versions of the recipe to use this archive folder instead of the official_releases folder.
I don't think qt guys commited  to maintaining stable urls. Ideally we'd use a server with stable url, doing redirections to the proper download
qt.io url

**Comment by uilianries** [comment]
Nice! thanks for sharing it!

**Comment by Croydon** [comment]
Closing because 5.11.3+ should work fine.
