### ISSUE TITLE
[spdlog] Wrong version of fmt used in v1.4.1 package

### ISSUE THREAD

**Issue by torfinnberset** [bincrafters/community#988]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **spdlog/1.4.1**

The newly released spdlog v1.4.1 package (#975) uses fmt library v5.3.0 (https://github.com/bincrafters/conan-spdlog/blob/875397d39282a132b63351e97696cc51a3043358/conanfile.py#L25), but according to the spdlog release notes, it should be using fmt v6.0.0 since spdlog v1.4.0: https://github.com/gabime/spdlog/releases

**Comment by gabime** [comment]
It can be used with 5.3.0 as well.

**Comment by uilianries** [comment]
I **can** != **should** be used with fmt 6.0.0

But we have a problem here: Since Conan Center Index adopted fmt, Bincrafters won't update their fmt package to 6.0.0, which means, we need to update spdlog using CCI version. However, we need to update ALL packages that are using fmt first to avoid any possible conflict e.g. `fmt/6.0.0@` x `fmt/5.3.0@bincrafters/stable`

**Comment by uilianries** [comment]
Anyway, accepting fmt/6.0.0 + spdlog/1.4.1 would be great!

**Comment by Croydon** [comment]
I made a spdlog/1.4.2 release with fmt/6.0.0
